### PR TITLE
Have probe query kube dns to find the app.

### LINKED ISSUE #1373: k8s: Remove App->Probe deployment ordering restriction
The Scope kubernetes resources require creating the Scope App service before the Scope Probe DaemonSet. This ordering restriction is inconvenient, and a showstopper for k8s package managers like [helm](http://helm.sh/), which don't include any support for ordering.

From https://github.com/TheNewNormal/kube-charts/blob/master/weavescope/manifests/scope-probe-ds.yaml#L28-L40 :

```yaml
        # We cannot refer to the Scope App with its Kubernetes Service
        # DNS name (weave-scope-app) directly because Docker doesn't
        # allow customizing the DNS servers (the Kubernetes DNS add-on
        # server in this case) of a container when it runs in the
        # host's network namespace (see
        # https://github.com/docker/docker/issues/10384#issuecomment-72069550
        # ). Instead, we use variable expansion on its service
        # environment variables.
        #
        # NOTE: Unfortunately this imposes a specific creation
        # ordering since the Scope App Service needs to be created first for
        # the service environment variables below to be accesible.
        - "$(WEAVE_SCOPE_APP_SERVICE_HOST):$(WEAVE_SCOPE_APP_SERVICE_PORT)"
```

Also, this has the disadvantage of the probes not picking up a new service IP if it's recreated.

We could fix this by somehow obtaining the IP of Kubernetes Cluster DNS Service IP and use Scope's [custom resolver](https://github.com/weaveworks/scope/blob/619c63a0a5f088ca6c25354da1e5627e35052dbc/probe/appclient/resolver.go#L59-L78) to resolve the App's service (`weave-scope-app`).

I don't see a simple immediate way to obtain the Cluster DNS Service IP (it normally lives in the separate system namespace so it won't appear in the environment variables). One option would be moving Scope to the system namespace.

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #1373

### CODE REVIEW

**Comment by tomwilkie** [comment]
Have tested with following change to the probe yaml, works well:

```diff
diff --git a/scope-probe-ds.yaml b/scope-probe-ds.yaml
index 5c23180..7b4c835 100644
--- a/scope-probe-ds.yaml
+++ b/scope-probe-ds.yaml
@@ -28,19 +28,7 @@ spec:
         - --probe.docker=true
         - --probe.kubernetes=true
         - --probe.weave.addr=
-        # We cannot refer to the Scope App with its Kubernetes Service
-        # DNS name (weave-scope-app) directly because Docker doesn't
-        # allow customizing the DNS servers (the Kubernetes DNS add-on
-        # server in this case) of a container when it runs in the
-        # host's network namespace (see
-        # https://github.com/docker/docker/issues/10384#issuecomment-72069550
-        # ). Instead, we use variable expansion on its service
-        # environment variables.
-        #
-        # NOTE: Unfortunately this imposes a specific creation
-        # ordering since the Scope App Service needs to be created first for
-        # the service environment variables below to be accesible.
-        - "$(WEAVE_SCOPE_APP_SERVICE_HOST):$(WEAVE_SCOPE_APP_SERVICE_PORT)"
+        - weave-scope-app.default.svc.cluster.local:4040
         securityContext:
           privileged: true
         resources:
```

**Comment by 2opremio** [comment]
> Have tested with following change to the probe yaml,

Did you also move the probe to `kube-system` namespace? Otherwise `KUBE_DNS_SERVICE_HOST` won't be available. 

I think it would be cleaner to do something like

```diff
diff --git a/scope-probe-ds.yaml b/scope-probe-ds.yaml
index 5c23180..7b4c835 100644
--- a/scope-probe-ds.yaml
+++ b/scope-probe-ds.yaml
@@ -28,19 +28,7 @@ spec:
         - --probe.docker=true
         - --probe.kubernetes=true
         - --probe.weave.addr=
-        # We cannot refer to the Scope App with its Kubernetes Service
-        # DNS name (weave-scope-app) directly because Docker doesn't
-        # allow customizing the DNS servers (the Kubernetes DNS add-on
-        # server in this case) of a container when it runs in the
-        # host's network namespace (see
-        # https://github.com/docker/docker/issues/10384#issuecomment-72069550
-        # ). Instead, we use variable expansion on its service
-        # environment variables.
-        #
-        # NOTE: Unfortunately this imposes a specific creation
-        # ordering since the Scope App Service needs to be created first for
-        # the service environment variables below to be accesible.
-        - "$(WEAVE_SCOPE_APP_SERVICE_HOST):$(WEAVE_SCOPE_APP_SERVICE_PORT)"
+        - --resolver "$(KUBE_DNS_SERVICE_HOST)"
+        - weave-scope-app.default.svc.cluster.local:4040
         securityContext:
           privileged: true
         resources:
```

instead of hardcoding the the variable name (which may not always be available depending on namespaces etc ... )

**Comment by tomwilkie** [comment]
> Did you also move the probe to kube-system namespace?

As a matter of fact, I did (a couple of days ago).

I can add a resolver flag if you like.

**Comment by tomwilkie** [comment]
Okay I don't understand why this doesn't work any more:

Looking up entries in skydns from the app seems to work:
```
Toms-MacBook-Pro:service twilkie$ docker exec -ti k8s_weave-scope-app.18b7593d_weave-scope-app-2ahs8_kube-system_19cce9e1-12c3-11e6-8c37-4e93ef53825d_e0f13214 /bin/sh

/home/weave # nslookup weave-scope-app.kube-system.svc.cluster.local 10.0.0.10
Server:    10.0.0.10
Address 1: 10.0.0.10

Name:      weave-scope-app.kube-system.svc.cluster.local
Address 1: 10.0.0.39
/home/weave # exit
```

But looking up entries from the probe doesn't:
```
Toms-MacBook-Pro:service twilkie$ docker exec -ti k8s_weave-scope-probe.44a42fdc_weave-scope-probe-41wfa_kube-system_1a0e3d5d-12c3-11e6-8c37-4e93ef53825d_a4023716 /bin/sh
/home/weave # nslookup weave-scope-app.kube-system.svc.cluster.local 10.0.0.10
Server:    10.0.0.10
Address 1: 10.0.0.10

nslookup: can't resolve 'weave-scope-app.kube-system.svc.cluster.local': Name does not resolve
```

I don't think its a iptables / kube proxy thing, as the probe can still talk to the app by service IP address.

**Comment by tomwilkie** [comment]
Actually ignore me, thats alpine `nslookup` being unhelpful:

```
/home/weave # dig @10.0.0.10 weave-scope-app.kube-system.svc.cluster.local +notcp

; <<>> DiG 9.10.2 <<>> @10.0.0.10 weave-scope-app.kube-system.svc.cluster.local +notcp
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18500
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;weave-scope-app.kube-system.svc.cluster.local. IN A

;; ANSWER SECTION:
weave-scope-app.kube-system.svc.cluster.local. 30 IN A 10.0.0.39

;; Query time: 5 msec
;; SERVER: 10.0.0.10#53(10.0.0.10)
;; WHEN: Thu May 05 13:25:31 UTC 2016
;; MSG SIZE  rcvd: 79
```

If I change resolve.conf to look at the skydns virtual IP it works:
```
/home/weave # vi /etc/resolv.conf 
/home/weave # nslookup  weave-scope-app.kube-system.svc.cluster.local 10.0.0.10
Server:    10.0.0.10
Address 1: 10.0.0.10

Name:      weave-scope-app.kube-system.svc.cluster.local
Address 1: 10.0.0.39
```

**Comment by tomwilkie** [comment]
@2opremio PTAL, works now

**Comment by 2opremio** [comment]
LGTM

**Comment by 2opremio** [comment]
Tests are failing though

**Pull request merged**
