### PR TITLE
Promote fixprobe and delete rest of experimental

### PR DESCRIPTION
**Pull request by jml**
We don't really need experimental, there are better ways of experimenting with code, and sometimes they fail the build, which gets in the way of making changes to scope. 

This PR deletes the experimental directory, but promotes `fixprobe`, which I'm told we use.

---
This change is [Reviewable](https://reviewable.io/reviews/weaveworks/scope/1646)

### CODE REVIEW

**Comment by tomwilkie** [comment]
Can we keep the example subdirectory?  It doesn't require building, and is very useful.

Otherwise I'm happy with this, but we should check with others.

**Comment by tomwilkie** [comment]
Am still happy, but I think you should also get @paulbellamy and @2opremio's LGTM.

**Comment by paulbellamy** [comment]
Maybe `s/extras/tools/` ?

**Comment by paulbellamy** [comment]
Not fussy about that though, LGTM.

**Comment by jml** [comment]
Really no preference at all. Will rename after @2opremio has had a chance to look, in case he has a preference.

**Comment by 2opremio** [comment]
LGTM

**Comment by jml** [comment]
There's already a `tools` directory, a git subtree that has our core build tools. Merging as-is. 

Thanks for the reviews!

**Pull request merged**
