### PR TITLE
Changelog for 0.10.0

### PR DESCRIPTION
**Pull request by paulbellamy**
I left out the code cleanup and refactoring PRs, as there are loads and they're not very interesting to users.

### CODE REVIEW

**Comment by paulbellamy** [comment]
raised https://github.com/weaveworks/scope/issues/653

**Comment by paulbellamy** [comment]
Seems that there was an edge-case on #627, where uncontained can be "connected" to itself. Not a release-blocker, so have filed https://github.com/weaveworks/scope/issues/656 to deal with it later.

**Comment by paulbellamy** [comment]
Waiting for https://github.com/weaveworks/scope/pull/646, then will rebase on master

**Comment by tomwilkie** [comment]
I've tested with the experimental/example app locally and the experimental/demo script to bring up a 2 host cluster on gce.  Apart from the one fixed issue, all looked good.  LGTM

**Pull request merged**
