### PR TITLE
Document how to access the Scope UI in k8s

### LINKED ISSUE #1390: Improve k8s instructions, indicating how to find the Scope App Service endpoint
See https://weaveworks.slack.com/archives/scope-public/p1461714841000067

### PR DESCRIPTION
**Pull request by 2opremio**
Fixes #1390

### CODE REVIEW

**Comment by tomwilkie** [comment]
Do you think this should target anita's docs branch?

**Comment by 2opremio** [comment]
That's going to take a while so I'd rather have it in the README earlier (it came from a user request). I will make sure we add it to the main docs.

cc @abuehrle

**Comment by tomwilkie** [comment]
LGTM.

**Comment by abuehrle** [comment]
@2opremio I'm planning to roll these docs out this week.

**Pull request merged**
