### PR TITLE
Branding

### PR DESCRIPTION
**Pull request by davkal**
* add weave scope logo
* add weave colors

### CODE REVIEW

**Comment by tomwilkie** [comment]
LGTM

**Comment by davkal** [comment]
Still need to add official weave colors to main.less and base the gray on weave's charcoal gray.

**Comment by davkal** [comment]
Before:
screen shot 2015-05-18 at 12 35 06

**Comment by davkal** [comment]
After:
screen shot 2015-05-18 at 12 53 59

It's a bit more blue-ish because weave's base charcoal color is blue-ish.

**Comment by peterbourgon** [comment]
:dango:!

**Pull request merged**
