### PR TITLE
[WIP] Minor repositioning of controls

### PR DESCRIPTION
**Pull request by fbarl**
Moved around some controls as preparation for #2677 (see [latest mockups](https://www.dropbox.com/sh/45hq01047u7zfir/AABQugkx5FjhOOpIGilBB0pBa?dl=0&preview=170710timelineSketch2.png)) and addressed https://github.com/weaveworks/service-ui/issues/746 in the context of Scope.

##### Semantic grouping

* *Topologies* - top left
* *View selectors* (view mode, resource metrics) - top center
* *Time control* - top right
* *Filters* (topology options, search) - bottom left
* *Footer* (version, help, misc controls, zooming) - bottom right

##### Specific changes

* Moved the *Search bar* to the bottom left corner as it belongs to filters semantically.
* Moved the *Scope logo* down to the footer (next to version) and made it much smaller.
* Moved *Topologies* selector to the freed up space on the left and split it from the *View mode* selector.
* Centered *View mode* selector horizontally.
* Hidding the *CONFIGURE* button for Scope.

##### Notes

* We should consider moving the *Networks* button together with the view selectors (as is the case with resource metrics).

### CODE REVIEW

**Comment by rade** [comment]
screenshot?

**Comment by fbarl** [comment]
@rade Taken from my 1920 x 1080 pixels screen:

context-scope
context-cloud

**Comment by pidster** [comment]
I think I understand what you're trying to achieve, but I'm not at all keen on the weavescope logo moving down to the bottom.

**Comment by fbarl** [comment]
@pidster Are we putting this story on hold before we organize around the general Scope interface redesign project or shall we proceed with the code review?

I do see this particular PR as a prerequisite for #2677 (and #2686) though, unless we want to hack the mockups a bit in the meantime.

**Comment by pidster** [comment]
I don't think this is a pre-requisite, given our intent to fix the general problem. 
We should proceed with getting the timeline in and live with a bit of clutter until we can deal with that separately.

**Comment by fbarl** [comment]
> I don't think this is a pre-requisite, given our intent to fix the general problem.

The reason I'm seeing it as a prerequisite rests on the assumption we made in the mockups that the timestamp (together with the red vertical line over the timeline) is always going to be horizontally centered. 

If we're not doing that yet, we'll have the red line shift more and more to the right on the lower screen resolutions (or more weird, be much to the left on wide screen, so most of the timeline would be showing the future by default, when at *now*). That's maybe not that terrible as a temporary solution, but IMO it does change the experience of using time travel.

**Comment by rade** [comment]
So the main issue really is the logo, since everything else easily shifts down. Yes?

**Comment by rade** [comment]
but the logo isn't present in Weave Cloud, which is the only thing that has timetravel for now, so that's not an issue.

**Comment by fbarl** [comment]
> So the main issue really is the logo, since everything else easily shifts down. Yes?

I'd say it's the logo + the search bar.

**Comment by rade** [comment]
You can shift down the search bar together with everything else.

**Comment by fbarl** [comment]
> You can shift down the search bar together with everything else.

You mean that the timestamp input field is put above search/topologies/etc., occupying its own vertical space and then we could center it horizontally? That could be another way to split the issues, but I'm afraid it will look very hacky - I'll start in that direction and see how it goes.

**Comment by pidster** [comment]
@fbarl a hack that minimises changes is better than making two bigger changes in succession.

**Comment by rade** [comment]
We have several issues open regarding the UI clutter: #1369 #1632

**Comment by fbarl** [comment]
Closing as this will be addressed as a part of #2800.

**Pull request closed without merging**
