### PR TITLE
Always center selected node

### LINKED ISSUE #615: Selecting node and moving canvas results in canvas not being in the place you'd expect
I find if I select & deselect nodes, moving the canvas around all the time, it quickly starts getting out of hand.  This interaction need some more thought.

Suggestion: when you have a node selected, don't allow the canvas to move?  Then when you deselect, put the canvas back to where it was before.  This might be more predictable.

### PR DESCRIPTION
**Pull request by davkal**
* dont allow panning while node is selected
* restore old panning position after deselect

Fixes #615

### CODE REVIEW

**Comment by tomwilkie** [comment]
A few comments from tests - Its a bit jerky going into and out of selected mode, and it doesn't deal with window resizing in selected mode very well - the nodes 'pop':

0ncltekrfe

**Comment by tomwilkie** [comment]
My understanding is:
- on click
- move canvas so focused node is in the middle
- move other nodes so they are arranged around it
- render them bigger, others as translucent
- on ‘un’ click, revert those changes

Would it be easier/look better is we didn’t move the canvas, just the nodes?  Eg on click, ‘lock’ the canvas, move the nodes to where we want them, render them bigger etc.  On ‘un’ click, put them back and unlock the canvas?

**Comment by davkal** [comment]
@tomwilkie I implemented the suggestions. PTAL

**Comment by tomwilkie** [comment]
With latest changes, I can zoom and drag in selected mode again.  Also, selected nodes seem to have gotten smaller, and I managed to get stuck in selected mode somehow, although I can't reproduce that.

However the not-moving-the-canvas-moving-the-node approach seems to work really well, and the resizing of the window not longer jumps around like before.  In fact its all much smoother.

**Comment by davkal** [comment]
@tomwilkie PTAL

**Comment by tomwilkie** [comment]
Yup, looking better.  1 issue - if you zoom (with two fingers on the track pad) whilst in selected mode, nothing happens (as expected).  But then, when you leave selected mode, and trigger a redraw (resize the window), the zoom gets applied.

**Comment by tomwilkie** [comment]
LGTM!

**Pull request merged**
