### PR TITLE
Hacky fix for integration/300

### PR DESCRIPTION
**Pull request by paulbellamy**
To help diagnose #546, and as a general improvement to the tests.

### CODE REVIEW

**Comment by tomwilkie** [comment]
Let see this pass, but I think you might have to add a "and wait for this set of container to exist or 5s" as well, as some of the cluster tests will give you 2 containers, and not the 4 you need.

**Comment by paulbellamy** [comment]
Not using `wait_for_reports` in the clustering tests, as checking a set of containers is in the report thing involves a bit of jq madness.

**Comment by paulbellamy** [comment]
Ditched wait_for_reports, as even on 300, it was returning after there were reports, but before there was nginx, and trying to wait for specific containers in the output descended into madness.

**Comment by tomwilkie** [comment]
@paulbellamy I figured out why 300 was failing; the curl was being run to quickly and erroring, and killing the subshell.

I'll fix in #542 and incorporate your changes too.

**Pull request closed without merging**
