### PR TITLE
Add lint script, run in circle ci.

### PR DESCRIPTION
**Pull request by tomwilkie**

### CODE REVIEW

**Comment by tomwilkie** [comment]
This is WIP; looks like static.go doesn't lint, so I deleted it, but now we need to get the UI building for this to be merged.

**Comment by peterbourgon** [comment]
static.go will never lint; can we make an exception in the linter?

UI building we can do today with @davkal

**Comment by tomwilkie** [comment]
I've added an exception, this is GTG

**Comment by peterbourgon** [comment]
:dango:

**Pull request merged**
