### PR TITLE
High contrast mode switch

### PR DESCRIPTION
**Pull request by davkal**
* added button to the bottom right to switch to higher contrast,
* suitable for projectors
* increased contrast between background and text colors
* thicker strokes around chart elements
* ensure yellow details panel backgrounds are darker

Addresses #874

### CODE REVIEW

**Comment by davkal** [comment]
Normal mode:

screen shot 2016-02-10 at 16 09 13

High contrast mode:
screen shot 2016-02-10 at 16 10 07

**Comment by davkal** [comment]
Ludacris contrast:

screen shot 2016-02-10 at 16 14 52

**Comment by peterbourgon** [comment]
Nice! Since this is a super-rare feature mostly for us when we give demos, what do you think of swapping the toggle from `SWITCH CONTRAST` to something smaller, for example a half-moon icon?

**Comment by foot** [comment]
Code looks good, had a bit of a poke into less but couldn't see a nice way to redefine vars more dynamically. There might be reload style hacks etc. It would be cool if we could just add a class to the app and have the contrast update.

- Switching from high-contrast mode back to normal mode requires clicking the change contrast button twice atm

**Comment by davkal** [comment]
After review feedback:

screen shot 2016-02-11 at 10 41 45

**Comment by foot** [comment]
Nice! LGTM.

I associate this icon more classically w/ contrast, but it doesn't have a nice inverse, personal pref. http://fortawesome.github.io/Font-Awesome/icon/adjust/

**Comment by davkal** [comment]
Changed the icon. Thx @foot

**Pull request merged**
