### PR TITLE
Simplifying backgrounds to match lightgray in service-ui and ui-compo…

### PR DESCRIPTION
**Pull request by bia**
…nents
Breaks unless service-ui is also updated to https://github.com/weaveworks/service-ui/pull/1672

The corresponding gray shift in Explore to addresses the issues in https://github.com/weaveworks/ui-components/pull/93
Trying to consolidate and simplify some colouring and settled on this after quite a few more more drastic attempts..
Is this enough contrast?

screen shot 2018-01-02 at 20 48 16

### CODE REVIEW

**Comment by rade** [comment]
The highlighting of the controls at the top is rather faint.

**Comment by bia** [comment]
What if I shift up the darkness of both 'secondary-color's?
It kind of bothers me that all of these nuanced shades don't appear anywhere else in the app.
screen shot 2018-01-03 at 09 15 17

**Comment by rade** [comment]
That looks fine.

**Comment by bia** [comment]
Thanks! That's fixed now.

screen shot 2018-01-05 at 17 46 10

**Comment by rade** [comment]
...which has just reminded me to ask... why is there such a huge gap between the top controls and the table?

Vertical space is precious here; the table should use as much as it can.

Separate issue, clearly.

**Comment by rade** [comment]
> why is there such a huge gap between the top controls and the table?

Ah, I think it's there to accommodate the expansion of the top when timetravelling.

**Comment by bia** [comment]
@rade, but it shouldn't be that way when in Live mode?

**Comment by rade** [comment]
> but it shouldn't be that way when in Live mode?

Ideally not, no. Have filed #3015.

**Pull request merged**
