### PR TITLE
Squash merged reports as they come out of the LIFO, not individual reports as they come in.

### LINKED ISSUE #227: Cross-host connects not showing in UI when connection traverses docker port mapping
conn

### PR DESCRIPTION
**Pull request by tomwilkie**
Helps #227

### CODE REVIEW

**Comment by peterbourgon** [comment]
What's the net effect?

**Comment by tomwilkie** [comment]
There is no guarantee that the merged reports coming out of the collector are the result of merging reports from multiple probes.  The way timeouts are configured right now makes it very unlikely (collector interval is 1s, probe is 2s).  This change makes it way more likely, and therefore makes the cross-host linking stuff behave as it should.

**Comment by tomwilkie** [comment]
Note that we do the pseudo node munging on the LIFO merged report, so this also brings the squashing in line with that.

**Comment by tomwilkie** [comment]
And we have to put this in 0.3.0

**Comment by peterbourgon** [comment]
Got it. Let's add a report_lifo_test.go with a test that ensures 2 sequential reports with different local_networks squash to the right thing.

**Comment by peterbourgon** [comment]
LGTM.

**Pull request merged**
