### PR TITLE
Allow resizing on attached pipes too.

### LINKED ISSUE #1977: kubernetes logs don't use full width

### PR DESCRIPTION
**Pull request by foot**
Fixes #1977

### CODE REVIEW

**Comment by errordeveloper** [comment]
It works in general, i.e. the terminal uses full-width:



And resizing affects environment variables:



However, having resized to a very large size, and making it smaller again leads to shell prompt way below the last visible line. I'm not sure if this is something we may be able to fix, or it's a more general issue, I still don't fully grasp how exactly this stuff works.

**Comment by errordeveloper** [comment]
> However, having resized to a very large size, and making it smaller again leads to shell prompt way below the last visible line. I'm not sure if this is something we may be able to fix, or it's a more general issue, I still don't fully grasp how exactly this stuff works.

Having said observed it my initial test, I am not able to reproduce it now... I think this may be a separate issue to do some kind of edge-case. I'll report if I see it again, this PR LGTM 👍

**Comment by 2opremio** [comment]
@errordeveloper The terminals (`>_`) are not relevant for this PR. Did you test the logs (attach)?

**Comment by 2opremio** [comment]
@foot It would be cool if the control icon could be placed on a top corner of the terminal window (to know what control triggered it)

**Comment by davkal** [comment]
LGTM

**Comment by errordeveloper** [comment]
I've retested with logs.

Here is first one, looks good.



However, making the window wider doesn't reflow the log lines.



But closing and re-opening works ok.



Making the window smaller and bigger again leave empty space...

**Comment by 2opremio** [comment]
Thanks @errordeveloper,  better late than never. Can you please create an issue with this?

**Pull request merged**
