### PR TITLE
Make image count sorted in the details panel

### PR DESCRIPTION
**Pull request by tomwilkie**

### CODE REVIEW

**Comment by paulbellamy** [comment]
Displays a bit oddly in the details panel:
screen shot 2016-02-24 at 15 22 59

**Comment by paulbellamy** [comment]
Wouldn't metadata formatted as integer still be sortable?

**Comment by tomwilkie** [comment]
Metadata is sortable, yes, but not sorted by default.

@davkal if we add a format field (or sort field) to a metadata row, can we have that sorted too?

We don't need to hold 0.13 up on this.

**Comment by davkal** [comment]
Yes, please specify the default sort (other than 1st metric) in the columns of a table:
```
columns: [{id, label, defaultSort: true}, ...]
```

**Pull request closed without merging**
