### PR TITLE
Set 'default' as the default namespace filter instead of 'all'

### LINKED ISSUE #1440: Set namespace filter to `default` instead of `all` by default
Reported by @janwillies on Slack.

### PR DESCRIPTION
**Pull request by paulbellamy**
Fixes #1440

### CODE REVIEW

**Comment by 2opremio** [comment]
LGTM

**Comment by 2opremio** [comment]
Actually, is the `default` ns always guaranteed to exist? Will this work if it doesn't?

**Comment by paulbellamy** [comment]
hmmm. good question.

**Comment by paulbellamy** [comment]
Ok, so we'll only set it to default if we have a default namespace. Need to check this on monday.

**Comment by 2opremio** [comment]
@tomwilkie Early trigger.

**Comment by tomwilkie** [comment]
Huh?

**Comment by 2opremio** [comment]
There was a fix to be made which I missed before the LGTM

**Comment by 2opremio** [comment]
Oh, I see paul fixed it already, please ignore me.

**Pull request merged**
