### PR TITLE
Adjust timeline zoom sensitivity on Firefox

### LINKED ISSUE #2768: Time Travel: zoom sensitivity wildly different between Chrome and Firefox
In Firefox, to zoom out from a range of 6 minutes to a range of 1 hour, takes 55(!) full drags of my scroll wheel (one drag is about 8 clicks, so about 440 clicks), which is way too insensitive.

On Chrome, it takes just 3 full drags.

For comparison, zooming by the same 10x factor on Google Maps takes just 13 clicks.

### PR DESCRIPTION
**Pull request by fbarl**
Resolves #2768 by taking the `defaultWheelDelta` logic from https://github.com/d3/d3-zoom.

Zooming transitions were made also animated to make them smoother (especially on Firefox which sometimes does discrete jumps).

**Edit**: Tracking of zoom events was wrapped into a debounce method to prevent excessive Mixpanel reporting.

### CODE REVIEW

**Comment by rade** [comment]
The FF performance is probably #2302.

**Comment by fbarl** [comment]
> The zoom track still seems a bit excessive. What do you hope to learn? If it's binary use vs non-use, maybe use some `once` logic, or otherwise massively turn up the debounce interval (request handling eats into drawing performance).

I hope to see at which *depth* the users are using the timeline, i.e. whether they are more interested in moving through minutes/hours/days/etc... With that in mind, I will increase `ZOOM_TRACK_DEBOUNCE_INTERVAL` from `1s` to `10s` and also replace the `durationPerPixelInMilliseconds` float with a rounded humanized time unit (`minutes`, `hours`, etc..) to make it easier to interpret the Mixpanel data.

**Comment by fbarl** [comment]
@davkal I've updated the PR.

@rade Maybe you'd want to test the FF behaviour (modulo lagging) before I merge it.

**Comment by rade** [comment]
> Maybe you'd want to test the FF behaviour (modulo lagging) before I merge it.

Nah, it can hardly have gotten worse ;)

**Pull request merged**
