### PR TITLE
Build in a container, use go1.5, vendor Dependancies, build for Darwin and Arm on Circle.

### LINKED ISSUE #530: Move entirely to Go 1.5, remove netgo cruft from Makefile
- Check for Go 1.5 during builds
- Remove all netgo cruft from Makefile and other scripts

### LINKED ISSUE #535: Vendor dependencies
Use GO15VENDOREXPERIMENT

### LINKED ISSUE #550: Ensure scope builds on Darwin & ARM as part of circle.
```
docker run -ti -e GOARCH=arm -v $(pwd):/go/github.com/weaveworks/scope golang:1.5 /bin/sh -c "cd github.com/weaveworks/scope && make app/scope-app probe/scope-probe"
```

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #535, Fixes #550, Fixes #530

With this change, make should build the scope container on a correctly configured Mac, using Docker Machine.

See #583 for more context.

### CODE REVIEW

**Comment by tomwilkie** [comment]
Latest: instead of vendoring whole repos in vendor/, `gvt` supports vendoring just the sub modules we actually use (it does this by default).  This reduced the number of files from ~18k to ~2.5k, which is a massive improvement.

The commands I ran to produce this were:
```
go list -f '{{join .Deps "\n"}}' ./app ./probe | grep -E '^(github.com|k8s.io)' | grep -v 'github.com/weaveworks/scope' | sort -u > deps
cat deps | xargs -n1 gvt fetch
```

To update the vendored dependancies, you can do a `gvt update github.com/foo/bar`, or a `gvt update -all`

**Comment by 2opremio** [comment]
Some numbers in my Vagrant box (using NFS):

```
scope $ git branch
  535-vendor
* master

scope $ time git checkout 535-vendor                                                                                                                                                       
Checking out files: 100% (2439/2439), done.
Switched to branch '535-vendor'
Your branch is up-to-date with 'origin/535-vendor'.

real    0m13.652s
user    0m0.192s
sys     0m0.904s

scope$ time git status
On branch 535-vendor
Your branch is up-to-date with 'origin/535-vendor'.
nothing to commit, working directory clean

real    0m0.898s
user    0m0.000s
sys     0m0.128s

scope$ time make clean                                                                                                                                                                    
go clean ./...
rm -rf scope.tar  app/scope-app probe/scope-probe client/build/app.js docker/weave

real    0m4.609s
user    0m0.452s
sys     0m0.876s

scope $ du -hs .
176M    .

scope $ docker pull golang:1.5.1
[...]
scope $ time make #fresh
[...]
real    3m7.191s
user    0m0.972s
sys     0m3.204s

scope $ touch report/id.go # second time
scope $ time make 
[...]
real    1m44.136s
user    0m0.336s
sys     0m2.560s

scope $ time make # third time without modifying anything (to measure overhead)
[...]
real    0m15.273s
user    0m0.328s
sys     0m2.648s
```

**Comment by tomwilkie** [comment]
Thanks for the timing info.  Are those times acceptable?  Note the slow down in build is due to go1.5, not the vendoring - I can't see a reason for the vendoring to make anything slower.

Your git status time seems fine, and the checkout time won't be a problem once the change goes in.  What do you think?

**Comment by tomwilkie** [comment]
Pls don't merge until we release 0.9

**Comment by 2opremio** [comment]
@tomwilkie Yep, I think it's fine (I just shared the numbers to show how it performed in a dev VM with shared FS).

**Comment by peterbourgon** [comment]
Works On My Machine™

LGTM

**Comment by paulbellamy** [comment]
Just trying out gocertifi, quick...

**Comment by paulbellamy** [comment]
Also, it runs the scope-probe build every time I do `make`...

**Comment by paulbellamy** [comment]
How do you run the tests with this?

`go test ./...`, rightfully says there are no dependencies... and `make test` is not a thing.

**Comment by paulbellamy** [comment]
Also, we should be running `go test` on circle...

**Comment by tomwilkie** [comment]
tools/test is run on circle; and I've got another PR open to add a make tests.

Peter has been running go test in the subdir he wants, but you're right, this will break that.  Tools will need updating for the vendoring.

**Comment by paulbellamy** [comment]
After f2f discussion, my main concern is that tools/test is not using the vendored deps, or same version of go.

**Comment by peterbourgon** [comment]
Ah, good catch. The vendoring seems to be incomplete. [Gist](https://gist.githubusercontent.com/peterbourgon/0666c67d846c3bbc5f3a/raw/0a29e13d561a8f6fcd7e77c93954aefcb6543aa5/gistfile1.txt). Not sure how it's working via `make`?

**Comment by tomwilkie** [comment]
Its not; circle it using tools/test, which does its own go gets.

I'm just fixing the always-rebuilding-the-exes problem, then I'll look into
this.

**Comment by peterbourgon** [comment]
Yep. This works fine via `env GO15VENDOREXPERIMENT=1 go test ./...` from any of the individual directories. Which is fine for me.

**Comment by tomwilkie** [comment]
@paulbellamy PTAL

I suggest we get this one in then fix the test issues, as its blocking paul fixing the SSL issues.

**Comment by paulbellamy** [comment]
LGTM, we should probably also apply similar to the frontend build at some point.

**Comment by paulbellamy** [comment]
Actually, I think this is missing a few deps.

**Comment by peterbourgon** [comment]
Apart from a longstanding panic bug when testing probe/endpoint on Darwin, this works fine for me:

```
ƒ for d in app common probe render report xfer
    pushd (pwd)/$d
    pwd
    env GO15VENDOREXPERIMENT=1 go test -v ./...
    popd
end
```

**Comment by tomwilkie** [comment]
@paulbellamy I think this one should be good.  Mind taking one last look?

**Comment by tomwilkie** [comment]
Last two tools updates were to --no-go-get and no-coverage-for-vendored-packages fixes.  Please don't ask me to squash them, I don't seem to be able to do it for subtrees.

**Comment by tomwilkie** [comment]
I count 2 LGTMs; quite a lot has gone in and @paulbellamy promises to give that a look tomorrow, after I has merged.

**Pull request merged**
