### PR TITLE
Sentence cased text everywhere

### PR DESCRIPTION
**Pull request by rndstr**
Follows Weave Cloud's direction of sentence case on most things.

### CODE REVIEW

**Comment by bowenli** [comment]
I think keeping the "by foo" makes sense since it describes the grouping.

**Comment by bia** [comment]
LmostlyGTM
Some spacing issues become even more prominent in sentence case.
screen shot 2018-05-11 at 12 04 53
I talked with @fbarl about it - the simplest solution would be to add about 5px more css padding around that text.

I am unable to `make` scope, so I'm not able to preview this properly. Will see if I can fix that today.

>I think keeping the "by foo" makes sense since it describes the grouping.

We're addressing this in #3163

**Comment by rndstr** [comment]
@bia just fixed the alignment and adjusted the padding.
scope-table-header

**Comment by bia** [comment]
Cool, anyways that looks better. Maybe a little more space between the arrow and 'Processes'?

**Pull request merged**
