### PR TITLE
Bump tools subtree and fix integration tests

### PR DESCRIPTION
**Pull request by 2opremio**
* Bump tools subtree
`git subtree pull --squash --prefix tools/ git@github.com:weaveworks/build-tools.git master`
* Revert changes from to tools subtree incorrectly done locally
* Fix integration tests, by fixing problems introduced locally (by #2068) and remotely (fixed by https://github.com/weaveworks/build-tools/pull/65)
* Make integration tests more robust

### CODE REVIEW

**Comment by 2opremio** [comment]
It needs the linter fixes from #2068

**Comment by 2opremio** [comment]
@iaguis Continuing with #2068, this removes your linter changes in `tools/lint` by the upstream version.

**Comment by 2opremio** [comment]
It seems that the shellcheck fixes in build-tools broke the integrations tests. For instance https://github.com/weaveworks/build-tools/commit/83d5bd1f0e0132a88f55aab71735f351548a2860#commitcomment-20521055

There are still some errors I am debugging now.

**Comment by iaguis** [comment]
> It seems that the recent shellcheck fixes in build-tools broke the integrations tests. For instance weaveworks/build-tools@83d5bd1#commitcomment-20521055
> 
> There are still some errors I am debugging now.

I see, I fixed some errors like that one but I missed the ones breaking integration tests because they don't run on our CI. Sorry about that :(

**Comment by 2opremio** [comment]
@iaguis No worries, so far the problems come from fixes done upstream

**Pull request merged**
