### PR TITLE
Fix issues in k8s yaml files

### PR DESCRIPTION
**Pull request by Akash4927**
- Change `apigroups` to `apiGroups` in cluster-role.yaml
- Change `resourcenames` to `resourceNames` in cluster-role.yaml
- Add `selector` in deploy.yaml and ds.yaml

Signed-off-by: Akash Srivastava <akash.srivastava@openebs.io>

fixes: #3400

### CODE REVIEW

**Comment by dholbach** [comment]
Looks like the namespace 'weave' needs to be created still:
```
daniel@reef examples (⎈ |minikube:default)]$ kubectl apply -f k8s/
clusterrolebinding.rbac.authorization.k8s.io/weave-scope created
clusterrole.rbac.authorization.k8s.io/weave-scope created
namespace/weave created
podsecuritypolicy.extensions/weave-scope created
serviceaccount/weave-scope created
service/weave-scope-app created
Error from server (NotFound): error when creating "k8s/deploy.yaml": namespaces "weave" not found
Error from server (NotFound): error when creating "k8s/ds.yaml": namespaces "weave" not found
[daniel@reef examples (⎈ |minikube:default)]$
```

**Comment by dholbach** [comment]
Only slightly related to this PR: is this the best way to spin up Scope in a kubernetes environment (asking for the contributor in 3149 for example).

Shall we document this somewhere? E.g. 
 - spin up minikube
 - apply example/k8s
 - port-forward to access weave-scope-app

Or is there a better way?

(And thanks Akash for looking into this issue!)

**Comment by satyamz** [comment]
@dholbach steps look good to me. Minor feedback on the above steps,
 
- We need to include installation of Docker.
- Scope app service can be exposed as a `NodePort` on the local setup. (Sometimes, namespace & other filters doesn't work behind `kube-proxy` and `port-forward`)

It'd be good if you can file an issue containing this info. I will have someone to send PR for the same.

Thanks.

**Comment by Akash4927** [comment]
I think for the local setup, `NodePort` is a good idea to access the Scope.

**Comment by dholbach** [comment]
I filed https://github.com/weaveworks/scope/issues/3406 for this. Thanks a lot.

**Comment by dholbach** [comment]
Are we happy with this PR now or do we want to change something here?

**Comment by satyamz** [comment]
Thanks!

**Pull request merged**
