### PR TITLE
ecs: Make service a parent of task

### PR DESCRIPTION
**Pull request by ekimekim**
Fixes https://github.com/weaveworks/scope/issues/2041

### CODE REVIEW

**Comment by 2opremio** [comment]
Did you test it in the UI?

**Comment by ekimekim** [comment]
not yet

**Comment by 2opremio** [comment]
We may need to modify the rendering code for service parents to show on the details panel (I am not sure).

**Comment by 2opremio** [comment]
I at least expect https://github.com/weaveworks/scope/issues/2040 to require changes in rendering.

**Comment by ekimekim** [comment]
Turns out the render code already does this implicitly, which is fine for now.
I may come back to this branch to remove that special-case and do it here properly, instead.

**Comment by 2opremio** [comment]
@ekimekim ping

**Comment by 2opremio** [comment]
@ekimekim re-ping  :)

**Comment by ekimekim** [comment]
Closing in favor of https://github.com/weaveworks/scope/pull/2436, since this is required for that and it's easier than stacking PRs on each other.

**Pull request closed without merging**
