### PR TITLE
Fix building outside of the container

### PR DESCRIPTION
**Pull request by 2opremio**

### CODE REVIEW

**Comment by paulbellamy** [comment]
You probably still want to have those depend on the container in the containerized case.

**Comment by 2opremio** [comment]
Why? They depend on it when `BUILD_IN_CONTAINER=true`

**Comment by paulbellamy** [comment]
LGTM, but would be worth having someone who uses this check it.

**Comment by tomwilkie** [comment]
Not lgtm. This will break things. Please wait until I'm back from holiday
and I'll explain.

**Comment by tomwilkie** [comment]
> Please wait until I'm back from holiday and I'll explain.

The dependancy between all the things built/run inside the container needs to exist so that if you change the build container (ie add a dependancy) then the executables are rebuilt inside the container.

The correct way to fix this is perhaps by clearing SCOPE_BACKEND_BUILD_UPTODATE and setting BUILD_IN_CONTAINER=false.  Although it will need more work.

**Comment by davkal** [comment]
Perhaps a separate target might help, e.g., `make outside`, which could touch the container uptodate files, so those those targets wont get triggered.

**Comment by tomwilkie** [comment]
@2opremio can we close this?

**Comment by davkal** [comment]
FWIW I'm alright with the status quo.

**Pull request closed without merging**
