### PR TITLE
Upgraded xterm.js to 2.2.3

### PR DESCRIPTION
**Pull request by jpellizzari**
Fix for #2121

New messages to stdout should no longer scroll down to the bottom.

@foot Please review.

### CODE REVIEW

**Comment by foot** [comment]
I couldn't get this going: I think this build process has changed a bit on the way to 2.2.3, code w/ `require()`s in it ends up in the browser, I had a little fiddle w/ webpack but no luck yet!

**Comment by jpellizzari** [comment]
@foot I added a more specific regex to the webpack config `noParse` field. It should resolve that require problem. Could you try again please?

**Comment by foot** [comment]
oh no, did you push up that webpack conf change or did i smush it w/ a `push -f`?

**Comment by jpellizzari** [comment]
@foot It came over in a rebase. It won't show in the diff, but it should show in the src

**Comment by foot** [comment]
Nice!

I was getting lots of warnings[0] when running `npm run build` so I fiddled w/ webpack.prod until they went away WDYT?


[0]
```
WARNING in ./~/xterm/lib/addons/terminado/terminado.js.map
Module parse failed: /Users/simon/weave/src/github.com/weaveworks/scope/client/node_modules/xterm/lib/addons/terminado/terminado.js.map Unexpected token (1:10)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:10)
    at Parser.pp$4.raise (/Users/simon/weave/src/github.com/weaveworks/scope/client/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/simon/weave/src/github.com/weaveworks/scope/client/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/simon/weave/src/github.com/weaveworks/scope/client/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/simon/weave/src/github.com/weaveworks/scope/client/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Users/simon/weave/src/github.com/weaveworks/scope/client/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/Users/simon/weave/src/github.com/weaveworks/scope/client/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/Users/simon/weave/src/github.com/weaveworks/scope/client/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/Users/simon/weave/src/github.com/weaveworks/scope/client/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/simon/weave/src/github.com/weaveworks/scope/client/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/simon/weave/src/github.com/weaveworks/scope/client/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/simon/weave/src/github.com/weaveworks/scope/client/node_modules/webpack/lib/Parser.js:902:15)
    at NormalModule.<anonymous> (/Users/simon/weave/src/github.com/weaveworks/scope/client/node_modules/webpack/lib/NormalModule.js:104:16)
    at NormalModule.onModuleBuild (/Users/simon/weave/src/github.com/weaveworks/scope/client/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/simon/weave/src/github.com/weaveworks/scope/client/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/simon/weave/src/github.com/weaveworks/scope/client/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/simon/weave/src/github.com/weaveworks/scope/client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/simon/weave/src/github.com/weaveworks/scope/client/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3)
 @ ./~/xterm/lib/addons ^\.\/.*$
```

**Comment by foot** [comment]
Terminal seems to work okay with or without the warnings fix though.

**Comment by jpellizzari** [comment]
My change was to the `noParse` field, but I think it effectively did the same thing as yours. I checked that `npm run build` and `npm run build-external` both run without warnings. Also, no warnings in the browser.

**Pull request merged**
