### PR TITLE
Change term.js library to xterm.js

### PR DESCRIPTION
**Pull request by jpellizzari**
From this issue: https://github.com/weaveworks/scope/issues/1940

Term.js is no longer supported, so this PR is to use xterm.js instead: https://github.com/sourcelair/xterm.js. There should be no change to what the users sees.

@davkal and @foot , I added a directory called `styles/vendor` for the xterm styles and did `@import vendor/xterm.less` right in the `main.less` file. Let me know if that is the preferred way to include vendor stylesheets.

### CODE REVIEW

**Comment by foot** [comment]
Nice one!

Small issues:
- term.js was swallowing keypresses when focused. xterm.js appears not to be doing that, our `App.onKeyPress|onKeyUp` is triggered on shortcut keys: (e.g. term loses focus on `/` as the search bar is focused). Some options:
 - add more code to the App key handlers to return immediately if showTerminal. eh
 - listen for and cancel key events on terminal wrapper element. ugh
 - something more elegant?
- ctrl-left-arrow / ctrl-right-arrow (which we hacked into vendor/term.js ourselves) don't work for me, confirm if they work for you? 

> the preferred way to include vendor stylesheets.

I don't think we have one atm but it would be nice to keep scope/vendor/* as small as possible. Perhaps either
 - In main.less:
`@import (inline) '../../node_modules/xterm/dist/xterm.css';`
 - Or (untested) something like `require('xterm/xterm.css')` in app/scripts/main.js

**Comment by jpellizzari** [comment]
- [ ] Intercept hotkeys while terminal is up
- [ ] Ctrl-Left/Right while terminal is up
- [ ] Ctrl-W to close terminal?
- [ ] Reconfigure stylesheets
- [ ] Test on a windows keyboard

**Comment by jpellizzari** [comment]
@foot I added a `showingTerminal` condition to the hotkeys handler. This would prevent any hotkeys from working while the terminal is open. Good idea or bad idea?
```javascript
  onKeyPress(ev) {
    const { dispatch, searchFocused, showingTerminal } = this.props;
    //...
    if (!searchFocused && !showingTerminal) {
      keyPressLog('onKeyPress', 'keyCode', ev.keyCode, ev);
      const char = String.fromCharCode(ev.charCode);
      if (char === '<') {
        dispatch(pinNextMetric(-1));
      } else if (char === '>') {
```
Re: the Ctrl-arrow keys not working, I am not able to reproduce. On my macbook, I am able to use option-arrows to go to the beginning of each word. Under the hood, xterm has a hidden textarea that does all the input, so it should do all the stuff you can do in a textarea. 

I also tried to do a option-arrow while using the `top` program within the shell to see if it does stuff, and it seems to move things around (not sure what it does, but things move around when I press the key).

Are you using a normal (windows) or a mac keyboard?

**Comment by foot** [comment]
Yes! option-arrows works \o/. My bad.

> This would prevent any hotkeys from working while the terminal is open. Good idea or bad idea?

This actually works as its only been applied to onKeyPress and not onKeyUp (which handles the `<esc>: closeDisconnectedTerminal` mapping).

We should clean it up though, will make a techdebt ticket...

**Comment by foot** [comment]
Perhaps `git rebase -i origin/master` and squash away the introduction of the xterm.css to keep history a little tidier and then LGTM!

**Pull request merged**
