### PR TITLE
Only show key metadata by default. Hide rest in a drawer.

### LINKED ISSUE #929: Add "Show More" for metadata in details panel
Pick top n things, put everything else behind a show more.

Container:
- ID
- State
- Command

Process:
- PID
- Command

Image:
- Image ID

Host:
- Kernel Version
- Uptime

### PR DESCRIPTION
**Pull request by paulbellamy**
Fixes #929

To make the interface cleaner, we can hide some non-key metadata by
default.

@davkal, this needs styling, js testing, and probably a js refactor.

### CODE REVIEW

**Comment by davkal** [comment]
Added styling and refactored JS.

**Comment by foot** [comment]
Code looks good!

Is there any other information that can potentially be displayed on a proc node? Otherwise its a bit annoying to click the `show more` button.

screen shot 2016-02-10 at 21 10 10

**Comment by paulbellamy** [comment]
We could just show everything by default on the process node. They'll never have any children anyway...

**Comment by davkal** [comment]
> We could just show everything by default on the process node. There's only 4 lines, and they'll never have any children anyway...

:+1:

**Comment by davkal** [comment]
Otherwise, LGTM

**Pull request merged**
