### PR TITLE
Add non-eBPF variants of tests 330 and 340

### PR DESCRIPTION
**Pull request by 2opremio**
Leftover from #2535 

Also, print debug information since they are flakey.

### CODE REVIEW

**Comment by rade** [comment]
Perhaps we should have two variants - ebpf and non-ebpf - of these tests, as we have for some others (300/301, 310/311).

**Comment by rade** [comment]
Could we grab the full report in these tests and make it available as a test artefact? That way we can investigate whether it is missing individual endpoints, processes, etc.

**Comment by 2opremio** [comment]
> Perhaps we should have two variants - ebpf and non-ebpf - of these tests, as we have for some 

Sure.

> Could we grab the full report in these tests and make it available as a test artefact?

Yep, I just reworked this PR to do that.

**Comment by rade** [comment]
> Yep, I just reworked this PR to do that.

Dumping the report on stdout isn't quite what I had in mind. I was suggesting to add the report to the test artifacts, just as we do for coverage data in the Weave Net CI. See https://circleci.com/gh/weaveworks/weave/9335#artifacts/containers/0 for an example.

**Pull request closed without merging**
