### PR TITLE
linter: fix punctuation and capitalization

### PR DESCRIPTION
**Pull request by alban**
Symptoms:
> app/control_router.go:44:38: error strings should not be capitalized or end with punctuation or a newline

This is blocking the build on: https://github.com/weaveworks/scope/pull/2020
https://circleci.com/gh/kinvolk/scope/363

### CODE REVIEW

**Comment by alban** [comment]
This time, the `lint` test passes fine, but it fails later:
```
$ cd $SRCDIR; make RM= client-test static

docker run  -ti -v /home/ubuntu/src/github.com/weaveworks/scope/client/app:/home/weave/app \
		-v /home/ubuntu/src/github.com/weaveworks/scope/client/test:/home/weave/test \
		weaveworks/scope-ui-build npm test
make: *** [client-test] Error 1

cd $SRCDIR; make RM= client-test static returned exit code 2
```

I cannot reproduce locally. I'll restart CircleCI to see if it helps.

**Comment by alban** [comment]
In another build, it failed in a more verbose way:
```
 RUNS  app/scripts/components/__tests__/node-details-test.js
 FAIL  app/scripts/components/__tests__/node-details-test.js
 RUNS  app/scripts/components/__tests__/node-details-test.js
  ● Test suite failed to run
    Cannot find module 'react/lib/ReactTestUtils' from 'node-details-test.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:144:17)
      at Object.<anonymous> (app/scripts/components/__tests__/node-details-test.js:3:47)

 RUNS  app/scripts/components/__tests__/node-details-test.js
```

**Comment by 2opremio** [comment]
@simon Mind taking a look at https://circleci.com/gh/kinvolk/scope/370 and see what's wrong? It may be a subtlety making it build differently for hem, IDK.

**Comment by foot** [comment]
We merged in some lib updates this afternoon which has fixed this, so if you rebase onto latest master you should be all good. I'm not sure when it was introduced. =/

**Comment by alban** [comment]
Thanks! This PR is green now.

**Pull request merged**
