### PR TITLE
vendor: bump tcptracer-bpf

### LINKED ISSUE #2796: eBPF not working on GKE
It appears that Container-Optimized OS (default on GKE), doesn't have the right flags enabled.

Probe log says:
```
<probe> WARN: 2017/08/04 10:44:53.730822 Error setting up the eBPF tracker, falling back to proc scanning: error while loading map "maps/tcp_event_ipv4": function not implemented
```

More info about the OS:
```
gke-cluster-1-default-pool-2e523339-361d / # modprobe configs
gke-cluster-1-default-pool-2e523339-361d / # zcat /proc/config.gz  | grep -i bpf
CONFIG_BPF=y
# CONFIG_BPF_SYSCALL is not set
CONFIG_NETFILTER_XT_MATCH_BPF=m
# CONFIG_NET_CLS_BPF is not set
# CONFIG_NET_ACT_BPF is not set
# CONFIG_BPF_JIT is not set
CONFIG_HAVE_BPF_JIT=y
# CONFIG_TEST_BPF is not set
gke-cluster-1-default-pool-2e523339-361d / # uname -a
Linux gke-cluster-1-default-pool-2e523339-361d 4.4.52+ #1 SMP Thu Jun 15 15:23:01 PDT 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.60GHz GenuineIntel GNU/Linux
gke-cluster-1-default-pool-2e523339-361d / # cat /etc/os-release
BUILD_ID=9460.64.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=efee0d7cfca9bf17817d7b5d796b56fa75c3b217
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=59
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=59
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos
gke-cluster-1-default-pool-2e523339-361d / #
```

### PR DESCRIPTION
**Pull request by iaguis**
This includes:

* an eBPF object built with a newer kernel (4.14)
* an increased threshold for guessing offsets, which is necessary for
the eBPF tracer to work on Google's Container-Optimized OS (used by
GKE)

Fixes #2796

### CODE REVIEW

**Comment by rade** [comment]
> an eBPF object built with a newer kernel (4.14)

What was the previous one built with?

What do we gain by the change?

Any compatibility issues?

**Comment by iaguis** [comment]
I started a 1.8.6 GKE cluster and deployed scope built with this PR to it. It seems to work fine:

```
> kubectl -n=weave logs weave-scope-agent-2tqx2
time="2018-01-26T13:36:24Z" level=info msg="publishing to: weave-scope-app.weave.svc.cluster.local:80" 
<probe> INFO: 2018/01/26 13:36:24.565466 command line args: --mode=probe --no-app=true --probe.docker=true --probe.docker.bridge=docker0 --probe.kubernetes=true weave-scope-app.weave.svc.cluster.local:80
<probe> INFO: 2018/01/26 13:36:24.565645 probe starting, version 9f3e7d3d, ID 503738f382bbe4de
<probe> INFO: 2018/01/26 13:36:25.233349 kubernetes: targeting api server https://10.11.240.1:443
<probe> WARN: 2018/01/26 13:36:25.323077 Cannot resolve 'scope.weave.local.': dial tcp 169.254.123.1:53: getsockopt: connection refused
<probe> WARN: 2018/01/26 13:36:25.326320 Error collecting weave status, backing off 10s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused. If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
<probe> WARN: 2018/01/26 13:36:25.329714 Error collecting weave ps, backing off 20s: exit status 1: "/usr/bin/weave: line 261: docker: not found\nERROR: Unable to parse docker version\n". If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
<probe> ERRO: 2018/01/26 13:36:25.345911 conntrack stderr:NOTICE: Netlink socket buffer size has been set to 8388608 bytes.
<probe> INFO: 2018/01/26 13:36:25.372591 cronjobs are not supported by this Kubernetes version
<probe> ERRO: 2018/01/26 13:36:25.888734 Error fetching app details: Get http://10.11.250.93:80/api: dial tcp 10.11.250.93:80: getsockopt: connection refused
<probe> ERRO: 2018/01/26 13:36:27.898776 Error fetching app details: Get http://10.11.250.93:80/api: dial tcp 10.11.250.93:80: getsockopt: connection refused
<probe> ERRO: 2018/01/26 13:36:29.896710 Error fetching app details: Get http://10.11.250.93:80/api: dial tcp 10.11.250.93:80: getsockopt: connection refused
<probe> INFO: 2018/01/26 13:36:32.903156 Control connection to weave-scope-app.weave.svc.cluster.local starting
<probe> INFO: 2018/01/26 13:36:34.316470 Publish loop for weave-scope-app.weave.svc.cluster.local starting
<probe> WARN: 2018/01/26 13:36:35.330659 Error collecting weave status, backing off 20s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused. If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
<probe> WARN: 2018/01/26 13:36:45.333296 Error collecting weave ps, backing off 40s: exit status 1: "/usr/bin/weave: line 261: docker: not found\nERROR: Unable to parse docker version\n". If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
<probe> WARN: 2018/01/26 13:36:55.375934 Error collecting weave status, backing off 40s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused. If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
```

You can try my image:

```
$ kubectl -n=weave get pod weave-scope-agent-2tqx2 -o jsonpath="{..image}" | cut -f1 -d " "
kinvolk/scope:iaguis-update-tcptracer-bpf-9f3e7d3d
```

**Comment by iaguis** [comment]
> What was the previous one built with?

We were building with whatever Fedora 25 has. Currently it's 4.13.16.

> What do we gain by the change?

The change is there because https://github.com/weaveworks/tcptracer-bpf/pull/52 got merged, which updates the docker image used to build tcptracer-bpf to Fedora 26.

We might get better code if the version of clang in Fedora 26 is newer, but nothing else.

> Any compatibility issues?

Not that I know of, since we use the offset guessing code it shouldn't matter what version is used to build the eBPF object nor what version the code runs on.

**Comment by rade** [comment]
> You can try my image

I have tested this in my existing GKE cluster, and it all works fine.

**Pull request merged**
