### PR TITLE
Faster conntrack parser

### PR DESCRIPTION
**Pull request by bboreham**
Profiling indicated that conntrack parsing was around 20% of the CPU time of the probe in Weave Cloud dev, so I wrote a scanner/parser instead of relying on `sscanf` and `split`.

Test run decoding a `conntrack -L` dump with 27,000 lines:

Before:
```
ok  	github.com/weaveworks/scope/probe/endpoint	19.174s
ok  	github.com/weaveworks/scope/probe/endpoint	17.206s
ok  	github.com/weaveworks/scope/probe/endpoint	17.377s
ok  	github.com/weaveworks/scope/probe/endpoint	18.486s
```

After
```
ok  	github.com/weaveworks/scope/probe/endpoint	3.817s
ok  	github.com/weaveworks/scope/probe/endpoint	4.411s
ok  	github.com/weaveworks/scope/probe/endpoint	3.702s
ok  	github.com/weaveworks/scope/probe/endpoint	4.022s
```

3.7/17.2=22%

Individual commits left for now in case I need to remember how I got here, but I would squash before merging. I don't recommend reading the individual commits for review.

### CODE REVIEW

**Comment by 2opremio** [comment]
Thanks @bboreham ! I shall take a look tomorrow 

It seems you have put quite a bit of work into this, wouldn't it have been better spent ditching the text parser and finishing https://github.com/vishvananda/netlink/issues/171 ? After https://github.com/vishvananda/netlink/pull/213 I think it wouldn't had taken too long.

**Comment by 2opremio** [comment]
Done: https://github.com/weaveworks/scope/issues/2495

@bboreham Mind fixing the linter problems?

**Comment by rade** [comment]
@bboreham what's happening with this?

**Comment by bboreham** [comment]
I guess we should close this since we prefer to use eBPF.

**Comment by bboreham** [comment]
We moved to using netlink in #3298.

**Pull request closed without merging**
