### PR TITLE
Add AMI docs into main docs, modified weave token instructions in one place

### PR DESCRIPTION
**Pull request by abuehrle**
@2opremio I've added the AMI doc to the main docs.  

Place the doc after installing.md and also changed the title, so we'll need to update the guide as well. 

Let me know if there is anything else we need to add in here. 

(Also modified an instance of the weave token. )

### CODE REVIEW

**Comment by 2opremio** [comment]
We need to fix the ECS guide when we merge this to get the ids from here

**Comment by abuehrle** [comment]
I'll make a PR over in Guides for this.

**Comment by 2opremio** [comment]
@abuehrle Please update the PR to cover the changes from https://github.com/weaveworks/integrations/pull/123 . I will happily update the guides and make https://github.com/weaveworks/integrations/blob/master/aws/ecs/README.md point to the website once this PR is deployed.

**Comment by abuehrle** [comment]
@2opremio addressed  weaveworks/integrations#123

**Comment by 2opremio** [comment]
@abuehrle The AMI IDs also changed

**Comment by 2opremio** [comment]
Please let me know when you deploy this so that I can update the guides and remove the docs from https://github.com/weaveworks/integrations/

**Pull request merged**
