### PR TITLE
Remove kubernetes_id column from the grid view.

### LINKED ISSUE #1759: Table-mode: do we need the k8s id columns?
All the k8s views have an ID column. But AFAICT it's just namespace/name, i.e. the composition of two fields we already show. So can we ditch this?

Somebody with knowledge of k8s and what these fields actually mean needs to chime in here please.

### PR DESCRIPTION
**Pull request by foot**
Redundant info

Fixes #1759

### CODE REVIEW

**Comment by davkal** [comment]
Wouldnt it make more sense not to include the field in the backend report in the first place?

**Comment by foot** [comment]
Not sure, ids can often be handy though. I'll have a quick look.

**Comment by davkal** [comment]
Code works.

> Not sure, ids can often be handy though. I'll have a quick look.

The original ticket said the field has useless information. So why not drop the field? 

WDYT @rade @2opremio ?

**Comment by 2opremio** [comment]
> WDYT @rade @2opremio ?

I think you are right and I started to completely remove the ID (namespace/resource_name) ... but then I realized we are also using them for the ranks. I could keep it just for the ranks but I think it would be fine to simply provide the namespace instead (nodes with the same namespace seem to be getting the same color anyways).

@davkal Can you check if this change would be acceptable?

**Comment by rade** [comment]
Let's please not make #783 worse. See also https://github.com/weaveworks/scope/pull/1567#issuecomment-225641062

**Comment by davkal** [comment]
You can keep the ID, we simply dont need the *field* `kubernetes_id` in the nodes' metadata.

**Comment by 2opremio** [comment]
> Let's please not make #783 worse

That's what I am asking, it seems we are only using the three first letters of the rank anyways.

> You can keep the ID, we simply dont need the *field* `kubernetes_id` in the nodes' metadata.

I know I can keep it, but it would be nice to completely remove it if it doesn't make a difference (if it makes a difference then I can simply reconstruct the ID with the namespace and the name in the app without needing to move the ID value around). From a quick look at the JS code from @paulbellamy it seems that it doesn't but I would like to get a confirmation.

**Comment by rade** [comment]
>  it seems we are only using the three first letters of the rank anyways.

Right now we are, but that must change.

**Comment by 2opremio** [comment]
> Right now we are, but that must change.

Fair enough, then I will simply generate the exact same ranks in the app (concatenating the namespace and name), without requiring to pass the derivate ID from probe to app.

**Comment by davkal** [comment]
A change here should not affect rank values, whatever it's used for. This PR should only result in the `kubernetes_id` field not showing up for nodes. It's being read from a node's metadata object, so instead of filtering it from there in JS, I suggested of removing it from the metadata.

**Comment by rade** [comment]
agreed. ditch `kubernetes_id` but leave ID well alone - if we want to make changes there let's do that in a separate issue/PR.

**Comment by 2opremio** [comment]
> agreed. ditch `kubernetes_id` but leave ID well alone - if we want to make changes there let's do that in a separate issue/PR.

I already did remove it, but the ID was only carried internally between probe and app (so it shouldn't impact the UI)

**Comment by 2opremio** [comment]
I reverted the change in the UI and stopped reporting the ID from the probe.

**Comment by paulbellamy** [comment]
LGTM

**Pull request merged**
