### PR TITLE
scope: fix stop command for OSX

### PR DESCRIPTION
**Pull request by alepuccetti**
Before this patch, `scope stop` was not stopping scope-app

### CODE REVIEW

**Comment by alepuccetti** [comment]
PTAL

**Comment by 2opremio** [comment]
@alepuccetti Thanks a lot. Good catch! Can you please recreate the PR against branch `release-0.17.1` ?

**Comment by tomwilkie** [comment]
No need to recreate it, you can change the target now: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Comment by alepuccetti** [comment]
@tomwilkie too late 😝

**Comment by alepuccetti** [comment]
Closed in favor of https://github.com/weaveworks/scope/pull/1811

**Pull request closed without merging**
