### PR TITLE
Store a histogram of report sizes

### PR DESCRIPTION
**Pull request by jml**
I've verified locally that the data shows up and looks good.

---
This change is [Reviewable](https://reviewable.io/reviews/weaveworks/scope/1668)

### CODE REVIEW

**Comment by tomwilkie** [comment]
LGTM, might want to remove the s3 byte written metric through.

**Comment by jml** [comment]
Which metric is that?

**Comment by tomwilkie** [comment]
https://github.com/weaveworks/scope/blob/d4c66bfe5b934bf44ddd1b3d64f497dd17c692e2/app/multitenant/aws_collector.go#L63

**Comment by jml** [comment]
Thanks. The "s3" bit mislead me. 

Removed. Will merge on green unless I hear otherwise.

**Comment by tomwilkie** [comment]
Yeah sorry I thought it was s3, but it wasn't.

Merge when you're ready, it'll be autodeployed to dev.

**Pull request merged**
