### PR TITLE
Rename NewReport -> MakeReport

### PR DESCRIPTION
**Pull request by tomwilkie**
Depends on #178 & #180

### CODE REVIEW

**Comment by peterbourgon** [comment]
This PR includes both of those, correct?

**Comment by tomwilkie** [comment]
Yes as it depends on them.  I won't submit this until they are submitted, so eventually it'll just have one.

Conversely, I could rebase this against master and get it in before #178 if that makes it easier for you?

**Comment by peterbourgon** [comment]
If you can merge #178 and #180, I'll review this with the proper diff.

**Comment by tomwilkie** [comment]
I've merged #180 already, so here is this off master; no dependancies.

**Comment by peterbourgon** [comment]
LGTM

**Pull request merged**
