### PR TITLE
Add ECS instructions and badge to README

### PR DESCRIPTION
**Pull request by 2opremio**

### CODE REVIEW

**Comment by tomwilkie** [comment]
Can we put the badge with the launch instructions?  It doesn't match the other badges, which looks kinda naff.

Also, @abuehrle FYI these will need to be incorporated into the new docs.

**Comment by 2opremio** [comment]
I knew the badge could be controversial :)

>  It doesn't match the other badges, which looks kinda naff.

You mean the colors? I know, but I thought it would make the installation even more frictionless and self-explanatory for those familiar with cloud-formation (i.e. no need to even look for how to deploy on AWS, just click the button).

I could make it match the other badges but it would make it fail its purpose (it wouldn't be as recognizable anymore).

> Also, @abuehrle FYI these will need to be incorporated into the new docs.

Yes please. We should include the documentation of the AMIs (and by extension CloudFormation deployments) https://github.com/weaveworks/integrations/blob/master/aws/ecs/README.md

**Comment by paulbellamy** [comment]
Isn't the badge just a link to the ecs docs? I agree it looks a bit naff.

**Comment by 2opremio** [comment]
I will remove it then

**Comment by paulbellamy** [comment]
Maybe replace with a more obvious link to the guide in the aws section?

**Comment by paulbellamy** [comment]
On a related note, our readme is getting quite long. Maybe a table of contents?

**Comment by abuehrle** [comment]
I've incorporated the readme into the new docs, see #1416 . This needs adding to the restructured docs, though.

**Comment by 2opremio** [comment]
> Maybe replace with a more obvious link to the guide in the aws section?

I think that the link link to the cloud formation template in the aws section is pretty clear.

**Pull request merged**
