### PR TITLE
Highlight selected topology

### LINKED ISSUE #915: Make it more obvious which topology you're looking it
#884 will help here, but we could also make the topology selection at the top more visible.

Matthias said "when watching somebody use scope, I am confused as to whether I am looking at processes, containers, images, hosts"

### PR DESCRIPTION
**Pull request by davkal**
This PR tries to improve the highlighting of the selected topology label.
Trying to be consistent with new UI elements in the flux UI.  Fixes #915.

screen shot 2016-02-05 at 16 59 01

* added .btn-opacity to control opacity for buttons on hover/selected
  state

* increased contrast in topology link labels

* removed dark background from status to not confuse with topo links

### CODE REVIEW

**Comment by davkal** [comment]
No border:
screen shot 2016-02-05 at 17 00 03

**Comment by davkal** [comment]
Light border:
screen shot 2016-02-05 at 17 00 44

**Comment by davkal** [comment]
Dark selected:
screen shot 2016-02-05 at 17 21 10

**Comment by tomwilkie** [comment]
+1 for "No border" screenshot.

**Comment by tomwilkie** [comment]
summon @rade

**Comment by davkal** [comment]
Ready for review:
screen shot 2016-02-08 at 10 44 56

**Comment by peterbourgon** [comment]
That's Dark Selected; I thought we settled on No Border?

**Comment by davkal** [comment]
Review feedback:

screen shot 2016-02-08 at 12 22 54

**Comment by pidster** [comment]
LGTM

**Pull request merged**
