### PR TITLE
Update k8s installation instructions

### PR DESCRIPTION
**Pull request by 2opremio**
Improves #2497 

Let's please update the Scope instructions when the launch-generator _API_ changes. (CC @errordeveloper @marccarre )

### CODE REVIEW

**Comment by errordeveloper** [comment]
> ...when the launch-generator API changes

For the record, the API didn't break, we have made sure old behaviour stays as it was.

**Comment by 2opremio** [comment]
> For the record, the API didn't break, we have made sure old behaviour stays as it was.

I didn't say it broke, but the instructions did't work for the current k8s version.

**Comment by 2opremio** [comment]
I have now updated the docs.

I had to hack my way through by removing `search_type: Documentation` locally to make wordepress happy. It barked with:

```
2017/05/10 11:06:39 Loading 7 markdown files from site
2017/05/10 11:06:39 Error parsing site: parse site/ami.md: unknown attributes: map[search_type:Documentation]
```

(CC @abuehrle )

**Comment by errordeveloper** [comment]
My bad, I didn't review this properly! The path should be `/k8s/scope` and not `/k8s.yaml`.

**Comment by 2opremio** [comment]
Will fix

**Comment by 2opremio** [comment]
> My bad, I didn't review this properly! The path should be `/k8s/scope` and not `/k8s.yaml`.

But ...  the weave cloud help indicates using `/k8s.yaml`

**Comment by errordeveloper** [comment]
`/k8s.yaml` include Cortex and Flux, don't think we need to install those, and it requires the token, so it won't work for standalone Scope.

**Comment by 2opremio** [comment]
Aha, I see

**Comment by 2opremio** [comment]
That doesn't work:

```
manzanon:~ fons$ echo "https://cloud.weave.works/k8s/scope.yaml?k8s-version=$(kubectl version | base64 | tr -d '\n')"
Unable to connect to the server: dial tcp 192.168.99.101:8443: connect: host is down
https://cloud.weave.works/k8s/scope.yaml?k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiI2IiwgR2l0VmVyc2lvbjoidjEuNi4yIiwgR2l0Q29tbWl0OiI0NzdlZmMzY2JlNmE3ZWZmY2EwNmJkMTQ1MmZhMzU2ZTIyMDFlMWVlIiwgR2l0VHJlZVN0YXRlOiJjbGVhbiIsIEJ1aWxkRGF0ZToiMjAxNy0wNC0xOVQyMDozMzoxMVoiLCBHb1ZlcnNpb246ImdvMS43LjUiLCBDb21waWxlcjoiZ2MiLCBQbGF0Zm9ybToiZGFyd2luL2FtZDY0In0K
manzanon:~ fons$ curl https://cloud.weave.works/k8s/scope.yaml?k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiI2IiwgR2l0VmVyc2lvbjoidjEuNi4yIiwgR2l0Q29tbWl0OiI0NzdlZmMzY2JlNmE3ZWZmY2EwNmJkMTQ1MmZhMzU2ZTIyMDFlMWVlIiwgR2l0VHJlZVN0YXRlOiJjbGVhbiIsIEJ1aWxkRGF0ZToiMjAxNy0wNC0xOVQyMDozMzoxMVoiLCBHb1ZlcnNpb246ImdvMS43LjUiLCBDb21waWxlcjoiZ2MiLCBQbGF0Zm9ybToiZGFyd2luL2FtZDY0In0K
jse_shortmsg: >-
  Invalid Kubernetes version:
  "Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiI2IiwgR2l0VmVyc2lvbjoidjEuNi4yIiwgR2l0Q29tbWl0OiI0NzdlZmMzY2JlNmE3ZWZmY2EwNmJkMTQ1MmZhMzU2ZTIyMDFlMWVlIiwgR2l0VHJlZVN0YXRlOiJjbGVhbiIsIEJ1aWxkRGF0ZToiMjAxNy0wNC0xOVQyMDozMzoxMVoiLCBHb1ZlcnNpb246ImdvMS43LjUiLCBDb21waWxlcjoiZ2MiLCBQbGF0Zm9ybToiZGFyd2luL2FtZDY0In0K"
  / "Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2",
  GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean",
  BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc",
  Platform:"darwin/amd64"}" (base64-decoded).
jse_info: {}
message: >-
  Invalid Kubernetes version:
  "Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiI2IiwgR2l0VmVyc2lvbjoidjEuNi4yIiwgR2l0Q29tbWl0OiI0NzdlZmMzY2JlNmE3ZWZmY2EwNmJkMTQ1MmZhMzU2ZTIyMDFlMWVlIiwgR2l0VHJlZVN0YXRlOiJjbGVhbiIsIEJ1aWxkRGF0ZToiMjAxNy0wNC0xOVQyMDozMzoxMVoiLCBHb1ZlcnNpb246ImdvMS43LjUiLCBDb21waWxlcjoiZ2MiLCBQbGF0Zm9ybToiZGFyd2luL2FtZDY0In0K"
  / "Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2",
  GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean",
  BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc",
  Platform:"darwin/amd64"}" (base64-decoded).
statusCode: 400
body:
  code: BadRequestError
  message: >-
    Invalid Kubernetes version:
    "Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiI2IiwgR2l0VmVyc2lvbjoidjEuNi4yIiwgR2l0Q29tbWl0OiI0NzdlZmMzY2JlNmE3ZWZmY2EwNmJkMTQ1MmZhMzU2ZTIyMDFlMWVlIiwgR2l0VHJlZVN0YXRlOiJjbGVhbiIsIEJ1aWxkRGF0ZToiMjAxNy0wNC0xOVQyMDozMzoxMVoiLCBHb1ZlcnNpb246ImdvMS43LjUiLCBDb21waWxlcjoiZ2MiLCBQbGF0Zm9ybToiZGFyd2luL2FtZDY0In0K"
    / "Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2",
    GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean",
    BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc",
    Platform:"darwin/amd64"}" (base64-decoded).
```

**Comment by rade** [comment]
> Unable to connect to the server: dial tcp 192.168.99.101:8443: connect: host is down

kubectl can't talk to your k8s.

**Comment by 2opremio** [comment]
Yep, I noticed. I thought I would be using the client version ... which probably doesn't make sense. It works after fixing that.

BTW, a lot of users are going to run into this.

**Comment by rade** [comment]
> BTW, a lot of users are going to run into this.

A lot of users will have a kubectl that can't talk to their k8s?!?

**Comment by marccarre** [comment]
The `Server Version` is what you want, cause this is what really matters for your Kubernetes setup.
I can either:
1. relax the Launch Generator to fall back on the client version -- at the risks of a faulty setup; or
2. have a more explicit error when the `Server Version` isn't present.

I'd prob. go for 2., but any preference anyone?

**Comment by rade** [comment]
@marccarre File an issue and let's discuss there.

**Comment by 2opremio** [comment]
> A lot of users will have a kubectl that can't talk to their k8s?!?

People (including me) tend to follow instructions blindly. And particularly in instructions like

```
curl --silent --location --remote-name "https://cloud.weave.works/k8s/scope.yaml?k8s-version=$(kubectl version | base64 | tr -d '\n')"  
```

It's not clear whether kubectl should be able to speak to the cluster.

**Comment by marccarre** [comment]
@rade, @2opremio: weaveworks/launch-generator/issues/103

**Comment by abuehrle** [comment]
>I had to hack my way through by removing search_type: Documentation locally from all documents to make wordepress happy.

aack apologies @2opremio

**Pull request merged**
