### PR TITLE
Use a slice instead of a persistent list for temporary accumulation of lists

### PR DESCRIPTION
**Pull request by bboreham**
Reduce garbage created in `Merge()` and `Add()` from O(n) to O(1) by using a slice with enough capacity to hold the temporary head-portion of the list accumulated while walking the list to insert element(s).

(EDIT: except in the case where all merged data is newer, `Merge()` discards at least one of the input lists, so in that sense still creates O(n) garbage. I've reduced the internally-created garbage)

### CODE REVIEW

**Comment by tomwilkie** [comment]
Nice!  I can't see any problems with this.

**Comment by 2opremio** [comment]
Contributes to #1010 

Thanks @bboreham !

I have measured the impact this would have when using Scope to monitor our service, but it doesn't look very high. Here are the results of an `-alloc_objects -focus 'Metric'` heap profile of the:

* Probe: [pprof.localhost:4041.alloc_objects.alloc_space.001.pb.gz](https://github.com/weaveworks/scope/files/357307/pprof.localhost.4041.alloc_objects.alloc_space.001.pb.gz)

probe_alloc_objects_metric

* App: [pprof.localhost.alloc_objects.alloc_space.001.pb.gz](https://github.com/weaveworks/scope/files/357310/pprof.localhost.alloc_objects.alloc_space.001.pb.gz)

app_alloc_objects_metric


In what scenario did this make a considerable difference? Do you happen to have allocation profiles?

**Comment by 2opremio** [comment]
I've just realized that we are running Scope on the service with `--probe.processes=false` which will probably explain the difference. I will try again without this.

(No wonder I was surprised by the low CPU consumption).

**Comment by 2opremio** [comment]
After re-enabling the process topology and connecting the browser I get a closer behavior but not as close as I expected:

Here's the App's `-alloc_objects` heap profile (with 4 connected probes in the dev environment):

app_alloc_objects

And here's the same profile with focusing on revCons (`-focus 'revCons'`):

app_alloc_objects_revcons

So, this would reduce object allocation in ~5%.

Anyways, the change LGTM. @bboreham mentioned offline that this change was done after profiling the object allocation https://github.com/weaveworks/weavedemo , I will take a look at that next.

**Comment by bboreham** [comment]
The expected reduction is about half the allocations seen through `revCons`.  We save the accumulator list, but still have to build a new list.

**Pull request merged**
