### PR TITLE
Update docs to use K8s manifest generator

### PR DESCRIPTION
**Pull request by errordeveloper**

### CODE REVIEW

**Comment by errordeveloper** [comment]
@abuehrle this is for your branch 👍

**Comment by tomwilkie** [comment]
@errordeveloper pls target site/installing.md on the docs branch, not the readme.  The readme is about to be massively reduced in size.

**Comment by abuehrle** [comment]
@tomwilkie I've included @errordeveloper changes.  Let me push the updates.

**Comment by errordeveloper** [comment]
Ok, this looks odd now. This mean to be merged to `docs-reorg` branch and appear in #1416.

**Comment by abuehrle** [comment]
@errordeveloper I added this section to "Install Scope on Your Cluster". It couldn't be merged exactly as you wrote it, so please make sure that I haven't missed anything (there's a preview copy on the dev server as well, which I can't post here, but choose the 'latest' tag).  I would just close this branch.

**Comment by errordeveloper** [comment]
@abuehrle, I will take a look at what's on the dev site. I believe this PR should be closed now, or what do you want me to do, it has dozens of commits that do not relate to the title of the PR, and it was made to your branch...

**Comment by errordeveloper** [comment]
I'll make PR agains master once all docs rework had been merged.

**Pull request closed without merging**
