### PR TITLE
Extend plugin documentation

### PR DESCRIPTION
**Pull request by 2opremio**
* Add section to main README
* Add introduction to plugins-specific README

### CODE REVIEW

**Comment by 2opremio** [comment]
@paulbellamy @davkal PTAL

**Comment by davkal** [comment]
Could we get a quick-start section in the plugins README on how to use the example plugins?

**Comment by 2opremio** [comment]
You only need to type `make` in the example directory but we should make it explicit. Maybe we should include a README in each example directory?

@paulbellamy Can you please take over? I won't have time for this today.

**Comment by davkal** [comment]
I would add it to the central plugins readme. Let's try lowering barriers to get started. Definitely list the steps to do, and then tell them what they are expected to see if it works/doesnt work.

**Comment by paulbellamy** [comment]
@davkal added that. Mind proof-reading it?

**Comment by davkal** [comment]
LGTM

**Pull request merged**
