### PR TITLE
Release 1.10

### PR DESCRIPTION
**Pull request by bboreham**
See changelog for contents of release.

### CODE REVIEW

**Comment by satyamz** [comment]
Hi @bboreham This looks good! 
It'd be good if you can include these two files:
- https://github.com/weaveworks/scope/blob/master/examples/k8s/deploy.yaml
- https://github.com/weaveworks/scope/blob/master/examples/k8s/ds.yaml

**Comment by bboreham** [comment]
How do you mean "include" ?  If they're on master they will be in the release.

**Comment by satyamz** [comment]
I meant, if you can bump up the version in these files too.

**Comment by bboreham** [comment]
Oh, right.  Release process needs updating https://github.com/weaveworks/scope/wiki/Release-Process

Really we should add the single-probe-per-cluster config too, but the release doesn't need to wait for that.

**Comment by satyamz** [comment]
By this `single-probe-per-cluster`, you mean k8s probe?

**Comment by bboreham** [comment]
I mean the feature added at #3274 whereby we can stop all the per-node probes reporting Kubernetes info and just report it once for the whole cluster.

**Comment by satyamz** [comment]
Ok! This would be good addition. We can include that later in the example files. Let's go ahead with current changes.

**Pull request merged**
