### PR TITLE
circle.yml: deploy on a personal hub account

### PR DESCRIPTION
**Pull request by alban**
I would to do some changes in Scope and test my changes in Kubernetes,
following the guide on:
https://github.com/weaveworks/scope#using-weave-scope-with-kubernetes

For that, I need a Docker image of Scope hosted on a Docker hub and
reference that Docker image in my Kubernetes resource yaml file. Instead
of building Scope on my laptop and pushing it manually on my Docker Hub
account, I am using my CircleCI account to do this automatically.

This patch adds a deployment target in circle.yml. It uses the
environment variable $DEPLOY_PRIVATE_HUB_BRANCH from my CircleCI
settings and any push on a branch with a name matching ".*master" (the
branch name must end with "master") will trigger the deployment.

This change should not impact the build of the official Scope Docker
image because $DEPLOY_PRIVATE_HUB_BRANCH is not defined in the official
CircleCI settings (https://circleci.com/gh/weaveworks/scope).

### CODE REVIEW

**Comment by tomwilkie** [comment]
Hi @alban; I'd be tempted to update the `hub` target to work for you; protect it by a `test -n "$DOCKERHUB_USER"`, drop the `owner: weaveworks` line and add the `docker tag weaveworks/scope:latest $DOCKER_USER/scope:latest` line.  Then we can both use the same target.

**Comment by alban** [comment]
@tomwilkie that's sound good to me as well. I'll try that.

**Comment by alban** [comment]
This new version seems to work for me.

**Comment by alban** [comment]
@tomwilkie did it get pushed to the correct place?
https://circleci.com/gh/weaveworks/scope/3254
> The push refers to a repository [docker.io/tomwilkie/scope] (len: 1)

**Comment by tomwilkie** [comment]
mmm yes, it did not.  I forgot circle has my credentials.  We'll need another environment variable...

**Comment by alban** [comment]
I'm preparing another PR to fix this.

**Pull request merged**
