### PR TITLE
Add tests for short-lived connection between hosts and containers.

### LINKED ISSUE #448: Add end-to-end tests for short lived connections.

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #448

### CODE REVIEW

**Comment by tomwilkie** [comment]
@paulbellamy would you mind reviewing?

**Comment by tomwilkie** [comment]
Fixes #546, it wasn't the k8s change.  Sorry Paul.

**Comment by paulbellamy** [comment]
300 and 320 still fail for me locally. Also, seems like config.sh throws an error when jq fails: `
./config.sh: line 89: [: : integer expression expected`

```
Test ./100_launch_test.sh needs 1 hosts
Test ./105_launch_sans_weave_test.sh needs 1 hosts
Test ./110_shutdown_test.sh needs 1 hosts
Test ./200_clustering_2_test.sh needs 2 hosts
Test ./205_clustering_sans_weave_2_test.sh needs 2 hosts
Test ./300_internet_edge_test.sh needs 1 hosts
Test ./310_container_to_container_edge_test.sh needs 1 hosts
Test ./320_container_edge_cross_host_2_test.sh needs 2 hosts
>>> Running ./100_launch_test.sh on [192.168.48.11 192.168.48.12 192.168.48.13]
>>> Test ./100_launch_test.sh finished with success after 8.6 secs
>>> Running ./105_launch_sans_weave_test.sh on [192.168.48.11 192.168.48.12 192.168.48.13]
>>> Test ./105_launch_sans_weave_test.sh finished with success after 5.7 secs
>>> Running ./110_shutdown_test.sh on [192.168.48.11 192.168.48.12 192.168.48.13]
>>> Test ./110_shutdown_test.sh finished with success after 13.2 secs
>>> Running ./200_clustering_2_test.sh on [192.168.48.11 192.168.48.12 192.168.48.13]
>>> Test ./200_clustering_2_test.sh finished with success after 37.0 secs
>>> Running ./205_clustering_sans_weave_2_test.sh on [192.168.48.11 192.168.48.12 192.168.48.13]
>>> Test ./205_clustering_sans_weave_2_test.sh finished with success after 33.2 secs
>>> Running ./300_internet_edge_test.sh on [192.168.48.11 192.168.48.12 192.168.48.13]
>>> Test ./300_internet_edge_test.sh finished after 128.9 secs with error: exit status 1
Test short lived connections from the Internet
06bd9c52bb661bdd4a11cdd0bf2d2e82085a0c5e7fc68b8c8a6ac856568567e3
Weave Scope is reachable at the following URL(s):
  * http://10.0.2.15:4040/
  * http://192.168.48.11:4040/
  * http://10.32.0.1:4040/
96177e3b3e804793fedbdc97c14aaff6f278866ab05eeb02382f3a8730b9796e
./config.sh: line 89: [: : integer expression expected
./config.sh: line 89: [: : integer expression expected
Failed to find containers nginx The Internet after 60 secs
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
jq: error: null and array cannot have their containment checked
Failed to fing edge The Internet -> nginx after 60 secs
/home/vagrant/src/github.com/weaveworks/weave/test/assert.sh: line 80: 23457 Terminated              do_connections
test #2 "curl -s http://192.168.48.11:4040/api/topology/containers?system=show | jq -r '[.nodes[] | select(.label_major == "The Internet")] | length'" failed:
	expected "1"
	got "0"
test #3 "curl -s http://192.168.48.11:4040/api/topology/containers?system=show |  jq -r '.nodes[""].adjacency | contains(["96177e3b3e804793fedbdc97c14aaff6f278866ab05eeb02382f3a8730b9796e"])'" failed:
	expected "true"
	got nothing
2 of 3 tests failed in 126.918s.

>>> Running ./310_container_to_container_edge_test.sh on [192.168.48.11 192.168.48.12 192.168.48.13]
>>> Test ./310_container_to_container_edge_test.sh finished with success after 13.2 secs
>>> Running ./320_container_edge_cross_host_2_test.sh on [192.168.48.11 192.168.48.12 192.168.48.13]
>>> Test ./320_container_edge_cross_host_2_test.sh finished after 52.1 secs with error: exit status 1
Test short lived connections between containers on different hosts
548f843c0318a837f3f096416a3e72a9ad9f7c5efd3683ff86d59da841ce23b4
Weave Scope is reachable at the following URL(s):
  * http://10.0.2.15:4040/
  * http://192.168.48.11:4040/
  * http://10.32.0.1:4040/
5ab8401a3a664d0af492c5d3201a2ec580742592cbd0c5a24efd58e7967ecb19
Weave Scope is reachable at the following URL(s):
  * http://10.0.2.15:4040/
  * http://192.168.48.12:4040/
2897617a74ae3a0b563df825c88887da75c54adea2f6f2ee38d7fc55a95e9a21
4025e345d40ae19aa627fa53b24bddab70c16aa521d5923b86eb8a0bd89bbb02
Failed to fing edge client -> nginx after 10 secs
Found edge client -> nginx after 4 secs
test #3 "curl -s http://192.168.48.11:4040/api/topology/containers?system=show |  jq -r '.nodes["4025e345d40ae19aa627fa53b24bddab70c16aa521d5923b86eb8a0bd89bbb02"].adjacency | contains(["2897617a74ae3a0b563df825c88887da75c54adea2f6f2ee38d7fc55a95e9a21"])'" failed:
	expected "true"
	got "false"
1 of 6 tests failed in 50.872s.

>>> Ran 8 tests, 2 failed
>>> Fail ./300_internet_edge_test.sh
>>> Fail ./320_container_edge_cross_host_2_test.sh
```

**Comment by tomwilkie** [comment]
Hmmm, thanks.

300 is never going to pass locally (no internet node) - any suggestions on what to do?  A way of detecting its not running on gce, and just skipping it?

320 looks like a legitimate failure, one scope had the edge, and the other didn't.  I'll increase the timeout (10s is a little short).

And I'll try and make the jq stuff a bit less verbose.

**Comment by paulbellamy** [comment]
re: 300, any way to simulate an internet node? i.e. spoof the remote address of the connection?

**Comment by tomwilkie** [comment]
> re: 300, any way to simulate an internet node? i.e. spoof the remote address of the connection?

if you spoof it at the ip level, it won't connect (need to get packets back).  We could add code in scope to treat a given address as the internet, but I think thats going to far.  The test will run on circle.  Lets just skip it if run locally.  Unless you can think of another way...

**Comment by paulbellamy** [comment]
I'm not really clear why there's no internet node locally? We're still doing Curl requests against the node from some other random IP (the box running the tests).

**Comment by tomwilkie** [comment]
> I'm not really clear why there's no internet node locally? We're still doing Curl requests against the node from some other random IP (the box running the tests).

The test (in scope) for if a node should be treated as the internet is iff the IP address is not on a local network (according to your local IPs and subnets).  For the vagrant setup, the connection comes from an address on one of the local subnets.

**Comment by paulbellamy** [comment]
Would be nice if there were a cleaner way to detect GCE than grepping the hostname, but fine.

LGTM, then.

**Pull request merged**
