### PR TITLE
eBPF plugin improvements

### PR DESCRIPTION
**Pull request by 2opremio**
* Check that the protocol is TCP
* Support all HTTP methods
* Clear out tasks from table when they exit (required using task ids as table
  keys). A nice side effect of this is that we can tell apart tasks receiving 0
  req/second (i.e. tasks which currently aren't receiving any requests but were
  receiving requests at some point) from tasks which don't exist anymore.
  We report metrics fro the former.
* Simplify hash table key (no need to use a struct)

@paulbellamy @tomwilkie (and @dpw if he has the time) PTAL

### CODE REVIEW

**Comment by paulbellamy** [comment]
afaict, looks fine.

**Comment by dpw** [comment]
This approach has some major flaws if people try to make serious use of it .  We discussed them the other day, so I won't go into details.  I see it's in an "examples" directory, so maybe we don't intend people to use it seriously.  If so , I hope the context makes its status clear.

**Comment by 2opremio** [comment]
> This approach has some major flaws if people try to make serious use of it . We discussed them the other day, so I won't go into details.

Does the _Caveats_ comment in the ebpf code reflect that correctly?

**Comment by dpw** [comment]
> Does the Caveats comment in the ebpf code reflect that correctly?

Yes.  But very few people will look at comments in the code.

It's a question of context.  So for example, if people have to build the examples themselves, it's fine.

**Comment by 2opremio** [comment]
> It's a question of context. So for example, if people have to build the examples themselves, it's fine.

Right, as you mentioned, it's in the examples directory so I think it's fine. No code comments?

**Pull request merged**
