### PR TITLE
Migrate JS testing to Jest

### LINKED ISSUE #582: Build failing, not able to fetch phantomjs
Happened twice now:

https://circleci.com/gh/weaveworks/scope/1671

Anything we can do?

```
Error requesting archive.
Status: 503
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2",
  "encoding": null,
  "followRedirect": true,
  "headers": {},
  "strictSSL": true
}
Response headers: {
  "server": "nginx/1.6.2",
  "date": "Wed, 21 Oct 2015 11:08:41 GMT",
  "content-type": "text/html",
  "transfer-encoding": "chunked",
  "connection": "keep-alive",
  "cache-control": "no-cache"
}
Make sure your network and proxy settings are correct.

If you continue to have issues, please report this full log at https://github.com/Medium/phantomjs
npm WARN optional dep failed, continuing fsevents@1.0.2
```

### PR DESCRIPTION
**Pull request by davkal**
* does not require phantomjs (fixes #582 )
* reduced dependency install time by 20%
* keep using jasmine for test predicates

### CODE REVIEW

**Comment by tomwilkie** [comment]
Pls rebase.

**Comment by tomwilkie** [comment]
We seem to be missing a client lint from the circle file.  Did I accidentally remove that?

**Comment by davkal** [comment]
Linting is done via `eslint-loader` on build.

**Comment by tomwilkie** [comment]
Ah thanks.  LGTM in that case!

**Pull request merged**
