### PR TITLE
Support ARM64 build

### PR DESCRIPTION
**Pull request by arnulfojr**
Should address issue https://github.com/weaveworks/scope/issues/2110

### CODE REVIEW

**Comment by bboreham** [comment]
Have you tested this?

Has the situation noted in the comment changed?  (linking to http://stackoverflow.com/questions/31648793/go-programming-cross-compile-for-revel-framework)

**Comment by arnulfojr** [comment]
@bboreham I will check later today :)

**Comment by bboreham** [comment]
Hi @arnulfojr it would be great to get this merged but I really need to know it actually works on arm64.

**Comment by carlosedp** [comment]
Hi guys, I ended up submitting a PR (I don't know if I can push to this PR) on https://github.com/weaveworks/scope/pull/3537 that I built and confirm that works.

I currently run an ARM64 cluster with some SBCs and Scope is working perfectly.

**Comment by carlosedp** [comment]
Since #3537 have been merged. I believe this one can be closed.

**Pull request closed without merging**
