### PR TITLE
Don't need sudo when DOCKER_HOST is tcp.

### PR DESCRIPTION
**Pull request by tomwilkie**

### CODE REVIEW

**Comment by peterbourgon** [comment]
Does _anyone_ need sudo anymore? How about if you need sudo you just `sudo make`?

**Comment by tomwilkie** [comment]
I think a default install of docker on linux needs sudo to run things.  Doing a sudo make will result in stuff in you directory being owned by root.

**Comment by peterbourgon** [comment]
Okeedokey.

**Comment by paulbellamy** [comment]
I don't need the `SUDO` bit, so unless we need it in CI, I say scrap it.

**Comment by tomwilkie** [comment]
As discussed, we're going to keep the SUDO.

**Pull request merged**
