### PR TITLE
Use TCP for weave dns.

### LINKED ISSUE #1013: Autoclustering broke in master
Using df2c21e.

I have 7 nodes, and 24 A record in  DNS:
```
weave dns-lookup scope
10.17.0.75
10.17.0.78
10.32.0.1
10.17.0.77
10.44.0.0
10.40.0.1
10.17.0.81
10.40.0.1
159.203.67.181
159.203.101.140
159.203.121.136
10.36.0.3
10.38.0.1
10.17.0.76
10.34.0.1
159.203.113.192
10.46.0.0
159.203.116.168
159.203.117.174
10.17.0.79
159.203.67.181
10.17.0.80
104.236.254.144
10.17.0.75
```

I'm also seeing a bunch of WebSocket errors:
```
<app> INFO: 2016/02/23 16:30:12.510322 app starting, version df2c21e, ID 17f9bd301e68cf61
<probe> INFO: 2016/02/23 16:30:12.515089 probe starting, version df2c21e, ID 50b26fc69b6e7fee
<probe> INFO: 2016/02/23 16:30:12.515160 publishing to: localhost:4040
<app> INFO: 2016/02/23 16:30:12.518905 listening on :4040
<probe> INFO: 2016/02/23 16:30:12.529847 Control connection to 127.0.0.1:4040 starting
<probe> INFO: 2016/02/23 16:30:12.544301 docker container: collecting stats for 9b7199f981db026bed50512084b57a06ec5d9dd9bcd52077740b446477147552
<probe> INFO: 2016/02/23 16:30:12.546494 docker container: collecting stats for c0a37dda35b63143049e83d5797cf2392b834dd896444d610220063776af6f69
<probe> INFO: 2016/02/23 16:30:12.549708 docker container: collecting stats for 37aa24a556afd32970194f20b37de04f675fc96960ce6e5a1e29b92af5616348
<probe> INFO: 2016/02/23 16:30:12.550000 Publish loop for 127.0.0.1:4040 starting
<probe> INFO: 2016/02/23 16:30:12.551179 docker container: collecting stats for 888fc5936e00aa25b1449d6f9d5434456d46d8757a90ee6d2dc1ddc02e3a740d
<probe> INFO: 2016/02/23 16:30:12.552962 docker container: collecting stats for cec1a646c6859d4d3211724eef02dc02b70f3ab2a157cc6d13c3c1244af71103
<probe> INFO: 2016/02/23 16:30:12.554731 docker container: collecting stats for beeef7228b10b3152853f4c97506efddff5b74bd718a43d92253986ee0380826
<probe> INFO: 2016/02/23 16:30:12.558779 docker container: collecting stats for f2884f183cace00aa2431a4c089ce624ff01da986b91ca0e069a1320826a697b
<probe> INFO: 2016/02/23 16:30:12.561428 docker container: collecting stats for 1d357220874a9a6507fe066ef2db3215bd07403e2213b43d87b282ad999c1e48
<probe> INFO: 2016/02/23 16:30:12.569743 docker container: collecting stats for db935fe44b3d93587c2592459b00d74f9f221bd8b708147ce3ab7aca0135bf3a
<probe> INFO: 2016/02/23 16:30:12.574016 docker container: collecting stats for 87dd47dbcb6ac84dafe66eb32aa9e243d0501707b38c35126825973ccb3e4f04
<app> INFO: 2016/02/23 16:30:12.583393 Success updating weaveDNS
<probe> INFO: 2016/02/23 16:30:12.721139 docker container: collecting stats for 4ac2c5b62706d16ecb0aab74c2196016f13424a294f77226bb2fab7eff08c109
<probe> ERRO: 2016/02/23 16:30:12.735247 Error checking version: Unknown status: 400
<probe> INFO: 2016/02/23 16:30:12.880065 Success collecting weave info
<probe> ERRO: 2016/02/23 16:30:12.887196 docker container: error reading event, did container stop? read unix @->/var/run/docker.sock: use of closed network connection
<probe> INFO: 2016/02/23 16:30:12.887319 docker container: stopped collecting stats for 4ac2c5b62706d16ecb0aab74c2196016f13424a294f77226bb2fab7eff08c109
<app> INFO: 2016/02/23 16:31:13.394586 err: websocket: close 1005 
<app> INFO: 2016/02/23 16:31:27.412467 err: websocket: close 1005 
<app> INFO: 2016/02/23 16:31:28.905733 err: websocket: close 1005 
<app> INFO: 2016/02/23 16:31:29.725439 err: websocket: close 1005 
<app> INFO: 2016/02/23 16:31:34.176992 err: websocket: close 1005 
<app> INFO: 2016/02/23 16:31:59.308055 err: websocket: close 1001 
<app> INFO: 2016/02/23 16:32:04.233627 err: websocket: close 1001 
<app> INFO: 2016/02/23 16:32:09.288416 err: websocket: close 1005 
<app> INFO: 2016/02/23 16:32:10.495563 err: websocket: close 1005 
<app> INFO: 2016/02/23 16:32:11.351299 err: websocket: close 1005 
<probe> INFO: 2016/02/23 16:33:45.765915 docker container: collecting stats for 4e0d81f006a42d294a3aaea31edfc169cd775242a9efe02f1da478ea47efa81a
<probe> ERRO: 2016/02/23 16:33:46.232719 docker container: error reading event, did container stop? read unix @->/var/run/docker.sock: use of closed network connection
<probe> INFO: 2016/02/23 16:33:46.232757 docker container: stopped collecting stats for 4e0d81f006a42d294a3aaea31edfc169cd775242a9efe02f1da478ea47efa81a
<probe> INFO: 2016/02/23 16:33:53.902385 docker container: collecting stats for 42032fbda7b38762e628a32a3fab793144156a61e3cc7c21fe0f060ba0fec853
<probe> ERRO: 2016/02/23 16:33:54.065129 docker container: error reading event, did container stop? read unix @->/var/run/docker.sock: use of closed network connection
<probe> INFO: 2016/02/23 16:33:54.065171 docker container: stopped collecting stats for 42032fbda7b38762e628a32a3fab793144156a61e3cc7c21fe0f060ba0fec853
<probe> INFO: 2016/02/23 16:34:04.654315 docker container: collecting stats for 4611039db6fabf719017856c38e19c2931188de9a576bc6cf082ed9a0eb8d07d
<probe> ERRO: 2016/02/23 16:34:04.781010 docker container: error reading event, did container stop? read unix @->/var/run/docker.sock: use of closed network connection
<probe> INFO: 2016/02/23 16:34:04.781036 docker container: stopped collecting stats for 4611039db6fabf719017856c38e19c2931188de9a576bc6cf082ed9a0eb8d07d
<probe> INFO: 2016/02/23 16:34:10.502724 docker container: collecting stats for 74e4a9ce192b6627e85d7ccd0ccfce5c3d7db661365374234bc1c3dc15b4975f
<probe> INFO: 2016/02/23 16:34:10.646155 docker container: stopped collecting stats for 74e4a9ce192b6627e85d7ccd0ccfce5c3d7db661365374234bc1c3dc15b4975f
<app> INFO: 2016/02/23 16:34:41.379839 err: websocket: close 1005 
<app> INFO: 2016/02/23 16:34:46.124803 err: websocket: close 1005 
<app> INFO: 2016/02/23 16:34:49.204918 err: websocket: close 1005 
<probe> INFO: 2016/02/23 16:34:57.460021 docker container: collecting stats for a047b28d99c92b710b03b490f20a0a06301b94704ffa01192df427dc1036597a
<probe> ERRO: 2016/02/23 16:34:57.774014 docker container: error reading event, did container stop? read unix @->/var/run/docker.sock: use of closed network connection
<probe> INFO: 2016/02/23 16:34:57.774066 docker container: stopped collecting stats for a047b28d99c92b710b03b490f20a0a06301b94704ffa01192df427dc1036597a
```

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #1013

### CODE REVIEW

**Comment by rade** [comment]
We really should use golang's resolver. Alas it does not allow you to specify a server.

But if we have to do our own thing, we should at least do it correctly, i.e. try udp first and fall back to tcp if the answer is truncated. It's pretty simple to do and exactly [what golang does](https://golang.org/src/net/dnsclient_unix.go#L162)

**Comment by tomwilkie** [comment]
> But if we have to do our own thing, we should at least do it correctly, i.e. try udp first and fall back to tcp if the answer is truncated. It's pretty simple to do and exactly what golang does

Why?  Whats the downside to just using TCP?

**Comment by rade** [comment]
> Why? Whats the downside to just using TCP?

Protocol compliance. Alas you are off the hook. From [RFC 5966](https://tools.ietf.org/html/rfc5966#section-4):
> Regarding the choice of when to use UDP or TCP, Section 6.1.3.2 of RFC 1123 also says:
>
>      ... a DNS resolver or server that is sending a non-zone-transfer query MUST send a UDP query first.
>
>   That requirement is hereby relaxed.  A resolver SHOULD send a UDP query first, but *MAY elect to send a TCP query instead* if it has good reason to expect the response would be truncated if it were sent over UDP (with or without EDNS0) or for other operational reasons, in particular, if it already has an open TCP connection to the server.

**Comment by 2opremio** [comment]
@errordeveloper I have pushed an image called `weaveworks/scope:1038-dns-tcp` . Can you please test it? You will also have to change the version in the scope script (I think you already know the drill ... )

**Comment by tomwilkie** [comment]
@errordeveloper reports this worked on slack.  Ilya can you merge when you're happy?

**Comment by errordeveloper** [comment]
I will run a few more tests today to double-check.

**Comment by errordeveloper** [comment]
@rade I think we do have a good reason here, we do expect that response will be truncated, as we currently have several records for each host and in #1013 it end-ed up with 15 records for 5 hosts.

**Comment by rade** [comment]
> I think we do have a good reason here

yes, which is why I said "you are off the hook".

**Pull request merged**
