### PR TITLE
Add errcheck to our bin/test script (doesn't fit well with lint)

### PR DESCRIPTION
**Pull request by tomwilkie**

### CODE REVIEW

**Comment by tomwilkie** [comment]
Don't merge this until the tests pass, or we decide otherwise.

**Comment by tomwilkie** [comment]
Fixes #101

**Comment by peterbourgon** [comment]
Hmm. That's a very aggressive change. I'm fine with it for now, but we may later decide it's too much...

**Comment by tomwilkie** [comment]
Yup; if it turns out to be a pain or very dump, we can remove it.

**Pull request merged**
