### PR TITLE
update cloud desription and small edits

### PR DESCRIPTION
**Pull request by abuehrle**

### CODE REVIEW

**Comment by abuehrle** [comment]
@2opremio and @rade added a note to the Why Cloud section and also got a bit carried away and edited a bunch of other things. 

Please have a look.

**Comment by abuehrle** [comment]
@lukemarsden added a note to scope docs and some other small changes.

**Comment by 2opremio** [comment]
@abuehrle Mind rebasing?

**Comment by abuehrle** [comment]
Thought I did @2opremio?

**Comment by 2opremio** [comment]
@abuehrle something went wrong, there are unrelated commits

**Comment by abuehrle** [comment]
apologies @2opremio 

deleting this branch in favour of: 

https://github.com/weaveworks/scope/pull/2238

**Pull request closed without merging**
