### PR TITLE
Speed up npm bundle builds

### PR DESCRIPTION
**Pull request by davkal**
- [x] Use `include` option to point to app sources (reduces by 33%)
- [x] Try extracting vendor modules into own bundle
- [x] Have app, terminal-app, and common bundles

### CODE REVIEW

**Comment by foot** [comment]
Niccee, I get ~40s -> ~30s :+1: 

Turning sourceMaps off[0] gets another 5s, so down to about ~25s. Do they get used? I haven't had to debug anything in a prod env yet :).

```diff
diff --git a/client/webpack.production.config.js b/client/webpack.production.config.js
index 89744be..8072589 100644
--- a/client/webpack.production.config.js
+++ b/client/webpack.production.config.js
@@ -74,6 +74,7 @@ module.exports = {
     new webpack.DefinePlugin(GLOBALS),
     new webpack.optimize.CommonsChunkPlugin('vendors', 'vendors.js'),
     new webpack.optimize.UglifyJsPlugin({
+      sourceMap: false,
       compress: {
         warnings: false
       }
```

**Comment by foot** [comment]
Everything seems to still be working in dev/prod local/container.

LGTM

**Comment by davkal** [comment]
The `sourceMap: false` option in uglify gives me this error
```
ERROR in vendors.js from UglifyJs
TypeError: Cannot read property 'sections' of null
    at new SourceMapConsumer (/Users/david/weave/src/github.com/weaveworks/scope/client/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-map-consumer.js:24:21)
    at /Users/david/weave/src/github.com/weaveworks/scope/client/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:62:23
```

**Comment by davkal** [comment]
Turns out, it tried to uglify twice if `-p` was given. Now included `sourceMaps: false`.

**Pull request merged**
