### PR TITLE
Trim long container names and labels in details

### LINKED ISSUE #418: Trim Columns keys and Table titles in details pane
screen shot 2015-09-01 at 1 51 23 pm

Also, both for the keys and values, provide a way to view the full value when trimmed (i.e. hover-on) so that the user can view the full text.

### PR DESCRIPTION
**Pull request by davkal**
fixes #418

### CODE REVIEW

**Comment by tomwilkie** [comment]
Can confirm row labels are truncated as expected.

However, table headers are still wrapping:

screen shot 2015-09-02 at 17 04 24

**Comment by davkal** [comment]
I thought that was feature ;)

**Comment by 2opremio** [comment]
@davkal Maybe this should be addressesed somewhere else, but #418 also mentions there should be a way to display the full names (I suggested to do it on hover-on).

**Comment by davkal** [comment]
@fons that works already.

**Comment by davkal** [comment]
all right, lets keep this only for #418

**Comment by tomwilkie** [comment]
Can confirm this seems to all work as expected.  LGTM

**Pull request merged**
