### PR TITLE
Update google/gopacket library

### PR DESCRIPTION
**Pull request by bboreham**
To pick up a fix https://github.com/google/gopacket/pull/589 for Go 1.12

### CODE REVIEW

**Comment by dholbach** [comment]
I retried the integration-tests, but looks like they're broken for some reason.

**Comment by fbarl** [comment]
@bboreham Was there an issue manifestation in Scope that motivated this PR?

**Comment by bboreham** [comment]
> Was there an issue manifestation in Scope that motivated this PR?

Scope's build is still using an older Go, but on my dev machine with Go 1.12 this change is needed to compile.

**Comment by bboreham** [comment]
I found the unlikely reason for the test failure.

**Pull request merged**
