### PR TITLE
Report if newer version are availible in /api

### LINKED ISSUE #914: Report in the UI if new versions are availible
We can now detect this due to #907

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #914

### CODE REVIEW

**Comment by tomwilkie** [comment]
I've added the following to /api

```json
{
  ...
  "newVersion": {
    "version": "0.15.0",
    "downloadUrl": "https://...",
  }
}
```

**Comment by davkal** [comment]
screen shot 2016-04-21 at 19 13 00

**Comment by tomwilkie** [comment]
Thanks David!  @paulbellamy, mind reviewing?

**Comment by paulbellamy** [comment]
LGTM

**Pull request merged**
