### PR TITLE
Improve performance of docker stats obtention

### PR DESCRIPTION
**Pull request by 2opremio**
See https://github.com/weaveworks/scope/issues/812#issuecomment-186149907

### CODE REVIEW

**Comment by 2opremio** [comment]
OK, this completely takes away the decoding load. Yay!

probe

**Comment by 2opremio** [comment]
Acutually, they are not gone, but it's just 2.56% (0.18s) , and there is no contention reading the http bodies.

**Comment by 2opremio** [comment]
@tomwilkie PTAL

**Comment by tomwilkie** [comment]
LGTM!

**Pull request merged**
