### PR TITLE
Network colors from a scale

### PR DESCRIPTION
**Pull request by davkal**
* network-name independent
* all colors are unique and separated enough
* only 10 colors are available
* contains red and green

### CODE REVIEW

**Comment by rade** [comment]
Is this meant to fix #1592?

> network-name independent

Does that mean the same network may be coloured differently, depending on context?

**Comment by davkal** [comment]
It's a hack that fixes #1592 for network counts <= 10.

The colouring depends on the order of which we see the networks for the first time. That means it's stable while you keep the browser window open. It may be different if you reload or visit scope at a later point.

**Comment by foot** [comment]
I think its a good, safe solution for now, will work well for demos etc.

I'll give it a test.

**Comment by rade** [comment]
> network counts <= 10

what happens when you have more? Colours get re-used? Or does it explode?

**Comment by foot** [comment]
Repeats. category20 gives us 20 tho...

http://jsbin.com/kedozadozu/edit?html,js,output

**Comment by davkal** [comment]
cat20 is not distinct enough. It's 10 hues, with 2 different shades each:

https://github.com/d3/d3/wiki/Ordinal-Scales#categorical-colors

We could brew our own color scale...

**Comment by rade** [comment]
stick to cat10. merge it. move on to #783.

**Pull request merged**
