### PR TITLE
Release 1.2

### PR DESCRIPTION
**Pull request by 2opremio**
@davkal @foot @ekimekim @bowenli @jpellizzari @tomwilkie @abuehrle @pidster @errordeveloper @rade Please chip in by testing this release branch in the scenarios below and tick off what you tested afterwards (including your name at the end). Have a look at the CHANGELOG to prioritize your testing.

To make things  easier to test I have pushed the image `weaveworks/scope:release-1.2-9e33e7e`
Thanks!

- [ ] Start a 2 node cluster and leave a UI connected, watch for performance regression
- [x] Run a Scope cluster on ECS (mike)
- [x] Run Scope on https://github.com/microservices-demo/microservices-demo/ (mike)
- [x] Run Scope on Docker For Mac (Stuart)
- [ ] Start and stop Scope in standalone mode
  - [x] Linux (mike)
  - [ ] docker-machine
- [x] Connect probes from release candidate to Weave Cloud (fons)
  - [x] Local scope in probe-only mode connects to Weave Cloud and renders correctly
    - [x] dev
    - [x] prod
  - [x] Controls appear for containers and function correctly
    - [x] dev
    - [x] prod
  - [x] No new errors in logging or telemetry
    - [x] dev
    - [x] prod
- [ ] UI integration
  - [ ] Hot-reloading `cd client && npm i && npm start` and open http://localhost:4042
  - [x] UI under prefix path  `cd client && npm run build && npm start-production` and open http://localhost:4043/scoped/
  - [x] URL parameters: Run previous release and click around, keep UI open, start new release, reload page
- [x] UI features
  (To test: clone [microservices demo](https://github.com/microservices-demo/microservices-demo) and run `cd deploy/docker-compose && docker-compose up`)
  - [x] General: switch between topologies, see nodes and edges, details panel (Stuart)
  - [x] Zoom and pan, switch between topologies
  - [x] Topology filters: namespaces, system containers, etc. (Stuart)
  - [x] Metrics on canvas, try pinning/unpinning (Stuart)
  - [x] Search
    - [x] by container name
    - [x] by usage `cpu < 2%`
  - [x] Terminal (fons)
    - [x] Attach to container to see logs
    - [x] Exec to container and type `ls`
    - [x] Pop out terminal
  - [x] Contrast mode (fons)
  - [x] Download report
  - [x] Pause button

## Things to think about
- ECS Integration
- Kubernetes Integration
- CPU and memory usage

### CODE REVIEW

**Comment by 2opremio** [comment]
@simon found #2207 and #2208 . I think #2207 should be fixed before the release.

**Comment by 2opremio** [comment]
I updated the probes in WeaveCloud dev to run `weaveworks/scope:release-1.2-9e33e7e` and I don't see any regressions in CPU persformance.

It's not great (50% CPU) but better than 1.0 (https://github.com/weaveworks/scope/pull/1985#issuecomment-258826860 )

probe

**Comment by abuehrle** [comment]
I am just upgrading my environment with scope: scope:release-1.2-9e33e7e

Note also that there was an issue with Zipkin (tracer for microservices demo) hogging a fair share of resources as well: https://github.com/microservices-demo/microservices-demo/issues/598

**Comment by 2opremio** [comment]
Fixes https://github.com/weaveworks/scope/issues/2216

**Comment by jpellizzari** [comment]
LGTM!

**Comment by abuehrle** [comment]
scope stop with docker for mac:  https://github.com/weaveworks/scope/issues/2219

**Comment by ekimekim** [comment]
lgtm

**Comment by davkal** [comment]
lgtm

**Pull request merged**
