### PR TITLE
Backend build container

### PR DESCRIPTION
**Pull request by peterbourgon**
With :love_letter: to @davkal

### CODE REVIEW

**Comment by davkal** [comment]
The building works well. However, it builds a recent master, and not the current checkout. This would be important if I want to include my latest UI changes that have been compiled into static.go.
Any chance that could be made to work?

**Comment by peterbourgon** [comment]
Try that.

**Comment by davkal** [comment]
Seems to work! Let me try some more.

**Comment by davkal** [comment]
Yeah, works well, just tried it again. Really helpful.

**Pull request merged**
