### PR TITLE
Remove LatestMap, to reduce memory allocation

### PR DESCRIPTION
**Pull request by bboreham**
Previously, classes like `StringLatestMap` were implemented as a shim over `LatestMap`.
This meant that the memory allocations were:
[`ps.Map` leaf] -> [`interface{}` indirection] -> `LatestEntry` -> [`interface{}` indirection] -> [string contents]

Removing `LatestMap` and storing the entry via pointer rather than value gives us instead:

[`ps.Map` leaf] -> `stringLatestEntry` -> [string contents]

Also the `LatestEntry` was copied one more time on entry into the map. Thus this PR removes 50% of the memory allocations needed to create this particular structure, per entry.

(not counting the allocation for the map key)

### CODE REVIEW

**Comment by bboreham** [comment]
Some stats:

Running the following test:

```
package report                                                                                                                                                        
                                                                                                                                                                      
import "github.com/ugorji/go/codec"                                                                                                                                   
import "io/ioutil"                                                                                                                                                    
import "testing"

func TestDecode(t *testing.T) {
    b, _ := ioutil.ReadFile("fixed.msgpack")
    for i := 0; i < 100; i++ {
        r := Report{}
        handler := &codec.MsgpackHandle{}
        d := codec.NewDecoderBytes(b, handler)
        d.Decode(&r)
    }
}
```

where `fixed.msgpack` is a 1.5MB file supplied by Adam;

On master:

```
ok  	github.com/weaveworks/scope/report	2.798s
ok  	github.com/weaveworks/scope/report	2.502s
ok  	github.com/weaveworks/scope/report	2.492s
ok  	github.com/weaveworks/scope/report	2.504s
```

With this PR:

```
ok  	github.com/weaveworks/scope/report	1.849s
ok  	github.com/weaveworks/scope/report	1.735s
ok  	github.com/weaveworks/scope/report	1.761s
ok  	github.com/weaveworks/scope/report	1.785s
```

That's about a 30% speed-up, fastest to fastest.

**Comment by 2opremio** [comment]
Did you find generate_latest_map useful?

**Comment by 2opremio** [comment]
(i.e. we don't need to maintain it, so I hope it was helpful and you didn't update it because it was there)

**Comment by bboreham** [comment]
Yes, it's easier to edit the code once and generate twice, than to edit it twice.

**Pull request merged**
