### PR TITLE
Don't every store NEW conntrack flows (only every store updates).

### PR DESCRIPTION
**Pull request by tomwilkie**
This closes a small window where we might produce reports which contain flows that are NEW but have never seen an UPDATE, which can potentially be invalid.

### CODE REVIEW

**Comment by 2opremio** [comment]
> which can potentially be invalid.

When would this happen? Aren't there any situations in which we would want to track NEW flows with no UPDATES?

**Comment by tomwilkie** [comment]
> When would this happen? Aren't there any situations in which we would want to track NEW flows with no UPDATES?

TBH I don't know; I just observed in #1466 that all invalid flows fit the criteria of "they never saw an update".  This PR is an extension of #1466, to catch a small window where we might include flows which never saw an update.

I don't know for sure that all NEW flows which have never seen an UPDATE are invalid.  But this certainly made a big difference to the topology.

**Comment by tomwilkie** [comment]
Worth adding that all 'good' flows I've observed see an UPDATE almost immediately after a NEW, so I'm not particularly worries about missing flow.

**Comment by 2opremio** [comment]
OK, then LGTM

**Pull request merged**
