### PR TITLE
Dockerfile templates

### PR DESCRIPTION
**Pull request by adivjoseph**
added aarch64 ( go arm64) support using common Dockerfiles for X86_64 and aarch64

### CODE REVIEW

**Comment by 2opremio** [comment]
Much better, thanks. Would you mind modifying the circle conf so that it also builds for arm64?

**Comment by 2opremio** [comment]
Also, would you like to squash this in a specific way? (otherwise I will squash everything in a single when merging)

**Comment by adivjoseph** [comment]
yes please squash the everything into a single merg

**Comment by adivjoseph** [comment]
I have not used CircleCI but will look into it. What ARMv8 HW is available in your CI environment?

**Comment by 2opremio** [comment]
> What ARMv8 HW is available in your CI environment?

None, this would be just to test that it cross-compiles cleanly.

**Comment by 2opremio** [comment]
@adivjoseph friendly ping

**Comment by errordeveloper** [comment]
@adivjoseph are you still interested to work on this?

**Comment by 2opremio** [comment]
@adivjoseph are you still interested to work on this? I will close it for now, feel free to open another pull request if you want to keep working on it.

**Pull request closed without merging**
