### PR TITLE
Enable scroll locking on the terminal

### LINKED ISSUE #1481: Allow scroll-locking the terminal views
When using the attach control on a container or running commands with continuos output I cannot go back in the terminal history, since the terminal automatically scrolls down to the newest output.

The ideal behavior would be to only get automatic scrolling when the terminal is showing the very end of the output.

### PR DESCRIPTION
**Pull request by foot**
Fixes #1481

### CODE REVIEW

**Comment by foot** [comment]
@2opremio could you give this a quick test please!

**Comment by 2opremio** [comment]
Sure, I'll do that before EOD.

**Comment by davkal** [comment]
If I run the following and try to scroll up, the screen goes all black (before the fix it would jump around but show output.
```
while true; do find /etc; done                                
```

**Comment by foot** [comment]
Good one, that blows through the scroll back nice and quickly..

**Comment by 2opremio** [comment]
I am missing a side bar to indicate where am I in the history.

**Comment by 2opremio** [comment]
Also, I would expect scrolling to happen when selecting text and moving the mouse up. That is:

**Comment by foot** [comment]
Scrollbars are a nice to have, mentioned in #1940.

Scrolling up as we drag up is an interesting one. I'll mention it in that issue too.

**Comment by foot** [comment]
But you're looking for a way to export the contents of the terminal somehow. Other (less ideal but still) options:
- Copy terminal contents to clipboard
- Show terminal contents in some other mode that allows for better selection. (textarea/plain `<p>`s)

**Comment by foot** [comment]
Issue w/ this: cannot make a selection after having scrolled up.

**Comment by davkal** [comment]
Scrolling up works well, and the position stays there. Selections dont work when scrolled up, but that's mentioned. Definitely an improvement. LGTM

**Comment by 2opremio** [comment]
>  Selections dont work when scrolled up, but that's mentioned

Is there an issue for this?

**Pull request merged**
