### PR TITLE
Pass build tags to unit tests

### PR DESCRIPTION
**Pull request by bboreham**
On master, just after `make`:
```
$ time make tests
real	1m18.575s
```

On this branch:
```
$ time make tests
real	1m1.074s
```

Note this relies on https://github.com/weaveworks/build-tools/pull/103

### CODE REVIEW

**Comment by bboreham** [comment]
I realised those timings were skewed by `TestPipeRouter` taking 10 seconds longer in the second run.

This turns out to be because the mock Consul inside that test has a 10-second timeout that it may or may not hit at the end of the test.  I ran out of energy to fix that, alongside the 1-second timeout that it pretty much always hits retrying a closed connection.

Anyway, a fair comparison is 78 to 51 seconds.

**Comment by rade** [comment]
I had a go at re-basing this but ran away.

**Comment by rade** [comment]
@bboreham looks like your re-base didn't work :(

**Comment by bboreham** [comment]
@rade I am unclear what you are referring to.  CI tests passed when I clicked 'rebuild'.

**Comment by rade** [comment]
> CI tests passed when I clicked 'rebuild'.

It wasn't obvious that was going to happen.

LGTM

**Pull request merged**
