### PR TITLE
Show k8s labels and container env vars in the details panel.

### LINKED ISSUE #528: Expose Kubernetes namespaces and labels
Namespaces and labels can be presented with some kind coloured tag boxes. Namespace have resources associated with them also (#527).

### LINKED ISSUE #1207: It's a shame every node has DockerLabels
Even ones which can't have that, like processes, etc...

Raised in https://github.com/weaveworks/scope/pull/1204

### PR DESCRIPTION
**Pull request by tomwilkie**
Make the whole docker labels logic generic & template based, allowing the probe to create arbitrary tables in the details panel based on the key prefixes.

Fixes #1207, Fixes #528

### CODE REVIEW

**Comment by tomwilkie** [comment]
@davkal would you mind taking a look at the UI?  It doesn't seem to truncate these tables and show and +14 type expander:

screen shot 2016-04-19 at 10 57 20

**Comment by paulbellamy** [comment]
LGTM but I'd imagine @davkal will want to refactor the js into a Table component, inherited by NodeDetails/etc...

**Comment by tomwilkie** [comment]
Lets wait for an LGTM from @davkal

**Comment by tomwilkie** [comment]
Report for testing: 
[report.json.zip](https://github.com/weaveworks/scope/files/226284/report.json.zip)

**Comment by davkal** [comment]
* truncation worked
* react key was in the wrong place
* empty tables render section labels

Last two items are solved by
```diff
diff --git a/client/app/scripts/components/node-details.js b/client/app/scripts/components/node-details.js
index b7c2ced..bf8cd15 100644
--- a/client/app/scripts/components/node-details.js
+++ b/client/app/scripts/components/node-details.js
@@ -191,11 +191,17 @@ export default class NodeDetails extends React.Component {
             </div>
           )}
 
-          {details.tables && details.tables.length > 0
-            && details.tables.map(table => (<div className="node-details-content-section">
-            <div className="node-details-content-section-header">{table.label}</div>
-            <NodeDetailsLabels rows={table.rows} key={table.id} />
-          </div>))}
+          {details.tables && details.tables.length > 0 && details.tables.map(table => {
+            if (table.rows.length > 0) {
+              return (
+                <div className="node-details-content-section" key={table.id}>
+                  <div className="node-details-content-section-header">{table.label}</div>
+                  <NodeDetailsLabels rows={table.rows} />
+                </div>
+              );
+            }
+            return null;
+          })}
         </div>
       </div>
     );
```

**Pull request merged**
