### PR TITLE
Release 1.4.0

### PR DESCRIPTION
**Pull request by 2opremio**
@alban @fbarl @davkal @foot @ekimekim @bowenli @jpellizzari @abuehrle @pidster @errordeveloper @rade Please chip in by testing this release branch in the scenarios below and tick off what you tested afterwards (including your name at the end). Have a look at the CHANGELOG to prioritize your testing.

To make things easier to test I have pushed the image `weaveworks/scope:release-1.4-5af0a6d`
Thanks!

- [ ] Start a 2 node cluster and leave a UI connected, watch for performance regression
- [x] Run a Scope cluster on ECS [ML]
- [x] Run Scope on https://github.com/microservices-demo/microservices-demo/ [SW]
- [x] Run Scope on Docker For Mac [SW]
- [x] Start and stop Scope in standalone mode [AA]
  - [x] Linux [AA]
  - [ ] docker-machine
- [x] Connect probes from release candidate to Weave Cloud [SW]
  - [x] Local scope in probe-only mode connects to Weave Cloud and renders correctly
    - [x] dev
    - [x] prod
  - [x] Controls appear for containers and function correctly
    - [x] dev
    - [x] prod
  - [x] No new errors in logging or telemetry
    - [x] dev
    - [x] prod
- [ ] UI integration
  - [ ] Hot-reloading `cd client && npm i && npm start` and open http://localhost:4042
  - [ ] UI under prefix path  `cd client && npm run build && npm start-production` and open http://localhost:4043/scoped/
  - [ ] URL parameters: Run previous release and click around, keep UI open, start new release, reload page
- [x] UI features
  (To test: clone [microservices demo](https://github.com/microservices-demo/microservices-demo) and run `cd deploy/docker-compose && docker-compose up`)
  - [x] General: switch between topologies, see nodes and edges, details panel [AA]
  - [x] Zoom and pan, switch between topologies [AA]
  - [x] Topology filters: namespaces, system containers, etc. [SW]
  - [x] Metrics on canvas, try pinning/unpinning [SW]
  - [x] Search [AA]
    - [x] by container name
    - [x] by usage `cpu < 2%`
  - [x] Terminal
    - [x] Attach to container to see logs [SW]
    - [x] Exec to container and type `ls` [SW]
    - [x] Pop out terminal [SW]
  - [x] Contrast mode [AA] (*NOT PRESENT ANYMORE?* [SW])
  - [x] Download report [SW]
  - [x] Pause button [SW]
  - [x] SVG download [AA] (*ERROR* [SW])
  - [x] Reset view [SW]

## Things to think about
- ECS Integration
- Kubernetes Integration
- CPU and memory usage

### CODE REVIEW

**Comment by pidster** [comment]
Possible SVG error?

svg-error

**Comment by 2opremio** [comment]
@pidster Can you elaborate on how you got there?

**Comment by 2opremio** [comment]
@pidster The high contrast mode works for me, the icon is on the bottom right. You can't see it?

**Comment by 2opremio** [comment]
Saving as SVG works for me too.

**Comment by pidster** [comment]
@2opremio I see the following in Safari & Chrome:

controls-0

controls-1

Where should I be looking for contrast mode?

**Comment by pidster** [comment]
The report & the SVG...

[report-svg.zip](https://github.com/weaveworks/scope/files/1021535/report-svg.zip)

**Comment by 2opremio** [comment]
that's odd, I can see it without problems in Chrome:

screen shot 2017-05-23 at 11 10 59

**Comment by pidster** [comment]
Aha. Contrast mode is available on standalone Scope, but not SaaS.

**Comment by 2opremio** [comment]
I have created https://github.com/weaveworks/service-ui/issues/572

**Comment by 2opremio** [comment]
Unless somebody opposes, I will make the release in a couple of hours.

**Comment by ekimekim** [comment]
Sorry for late response - working fine in ECS afaict.

**Pull request merged**
