### PR TITLE
Grouping redesign

### PR DESCRIPTION
**Pull request by davkal**
Grouping was hard to understand, so the idea is to remove it and introduce sub-topologies instead:

```
Applications   Containers    Hosts  
by name        by image          
```

Related issue is #156

### CODE REVIEW

**Comment by davkal** [comment]
From the issue:

Current topos collection object is:

```json
{
    "name": "Applications",
    "url": "/api/topology/applications",
    "grouped_url": "/api/topology/applications-grouped",
    "stats": {
      "node_count": 12,
      "nonpseudo_node_count": 10,
      "edge_count": 13
    }
  }
```

I propose to nest sub-topologies:

```json
{
    "name": "Applications",
    "url": "/api/topology/applications",
    "stats": {
      "node_count": 12,
      "nonpseudo_node_count": 10,
      "edge_count": 13
    },
    "sub_topologies": [
       {
           "name": "by name",
           "url": "/api/topology/applications-by-name"
       }
   ]
}
```

FYI, the UI logic uses the last part of the url as the topology ID, e.g. `id(/api/topology/applications-by-name) -> applications-by-name` so it would be helpful if we can keep this prefix structure.

**Comment by peterbourgon** [comment]
@davkal now you get [this](https://gist.github.com/peterbourgon/109a047a42f77eedeac1) — all yours!

@tomwilkie maybe [this commit](https://github.com/weaveworks/scope/commit/086ff3b791979d39105d902b2d854bd927d0334d) is worth a quick review?

**Comment by peterbourgon** [comment]
Looks great! :shipit:

**Comment by tomwilkie** [comment]
At a brief look, https://github.com/weaveworks/scope/commit/086ff3b791979d39105d902b2d854bd927d0334d looks fine.

**Pull request merged**
