### PR TITLE
Stop hiding kubernetes topologies in the backend.

### LINKED ISSUE #1181: Hide Kubernetes topologies in the frontend, not the backend
When we go multitenant, the way we hide the kubernetes topologies won't work, as its shared state in the backend.

I'd like to be able to put a flag on the topology (hiddenIfEmpty or something) and have the frontend implement this.

Thoughts?

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #1181

TODO:
- [x] hide in the frontend if empty (using the `hide_if_empty` flag)

### CODE REVIEW

**Comment by tomwilkie** [comment]
A k8s report: [k8s_report.json.zip](https://github.com/weaveworks/scope/files/185982/k8s_report.json.zip)

**Comment by foot** [comment]
@tom we should be able to read `topo.stats.edge_count` to determine emptiness?

E.g.
```js
const visibleTopologies = topos.filter(t => !t.hide_if_empty || t.stats.node_count > 0);
```

**Comment by tomwilkie** [comment]
I would also look at `t.stats.filtered_nodes`

**Comment by foot** [comment]
@davkal r4r.

**Comment by tomwilkie** [comment]
+ @paulbellamy for backend review.

**Comment by davkal** [comment]
LGTM

**Pull request merged**
