### PR TITLE
Traffic control plugin

### PR DESCRIPTION
**Pull request by krnowak**
Depends on #1682. Last two commits are new.

### CODE REVIEW

**Comment by krnowak** [comment]
The CI failure looks unrelated.

**Comment by alepuccetti** [comment]
I am taking over this task and my branch contains these commits, so this PR can be close

**Comment by alban** [comment]
circle.yml currently pushes the main Docker image to [weaveworks/scope](https://hub.docker.com/r/weaveworks/scope/tags/). CircleCI should build and push the Docker image "weavescope-traffic-control-plugin" at the same time.

It could be done in a separate PR since the repository does not exit yet on https://hub.docker.com/u/weaveworks/.

**Comment by alepuccetti** [comment]
This is outdated by https://github.com/weaveworks/scope/pull/1837

**Pull request closed without merging**
