### PR TITLE
Add browser console logging for websocket to render times

### PR DESCRIPTION
**Pull request by davkal**
Print a log message when the time from websocket creation to first
render takes too long (100ms).

Activate logging via `localStorage["debug"] = "scope:web-api-utils"` in a browser console.

### CODE REVIEW

**Comment by 2opremio** [comment]
> Activate logging via `localStorage["debug"] = "scope:web-api-utils"` in a browser console.

Can you add this to `client/README.md`?

**Comment by davkal** [comment]
> Can you add this to client/README.md?

Has been there for a while.

**Comment by 2opremio** [comment]
> Has been there for a while.

Ops, I thought it was a new thing.

**Comment by foot** [comment]
LGTM

**Pull request merged**
