### PR TITLE
Fixes monospace font overlapping in terminal+linux

### LINKED ISSUE #3245: lines overlapping in terminals
Lines in the log output of pod shown in the weave scope terminal are overlapping. 

Environment Details:
Kubernetes Version: 1.9.6-gke

screenshot from 2018-06-29 15-49-51

### PR DESCRIPTION
**Pull request by foot**
Fixes #3245 

I believe this fixes the linked issue but I haven't had a chance to test under linux yet..

### CODE REVIEW

**Comment by rade** [comment]
I have just run this branch and my terminal is now not showing anything except cursor movement as I type; no characters are rendered at all.

**Comment by rade** [comment]
Works fine in Chrome though. Not FF.

**Comment by foot** [comment]
@rade thanks for testing! I will try something else...

**Comment by foot** [comment]
> I have just run this branch and my terminal is now not showing anything except cursor movement as I type; no characters are rendered at all.

I got a linux env of virtualbox+ubuntu18.04+firefox59.0.2 and I can repro and fix. I've tried installing and removing roboto in the linux vm. It might be falling back to a strange default font on your machine now.

I've popped in another font there as a bit of a hail mary, @rade could you please try testing this updated PR locally?

**Comment by rade** [comment]
Works fine now, though for some reason the first time I opened the terminal it was still blank.

**Comment by foot** [comment]
@jpellizzari not sure if you're on linux, but @rade and I verified that it works there. Code looks okay?

**Pull request merged**
