### PR TITLE
Use immutable objects for storing nodes in browser

### PR DESCRIPTION
**Pull request by davkal**
* makes checking for topology changes easier, which triggers fewer re-renders
* fix JS store tests with Immutables
* only update graph if topology changed

This was cherry-picked and patched from the cola-layout branch.

### CODE REVIEW

**Comment by tomwilkie** [comment]
Seems to work for me.  Didn't buy us much though?  LGTM

**Comment by tomwilkie** [comment]
Actually hold on; details panel doesn't seem to work anymore.

Just confirming its this change

**Comment by davkal** [comment]
This brings down browser CPU use considerably since it skips layout calls after topology data changes that wont have an effect on layout anyways. I wanted to add it now and use it as a base for other layout experiments.

**Comment by tomwilkie** [comment]
Yeah I can confirm the details panel is broken with this change - it always say node missing.

**Comment by davkal** [comment]
Will fix and add a test for this.

**Comment by tomwilkie** [comment]
@davkal do you want someone to review this again?

**Comment by davkal** [comment]
@tomwilkie yeah, that be great. I found other places where I want to use immutables in new branches.

**Comment by tomwilkie** [comment]
Okay can confirm details panel is fixed.  LGTM!

**Pull request merged**
