### PR TITLE
Fix order of tables in details panel to go from most to least granular.

### LINKED ISSUE #261: Order of tables in details panel depends on details on node id formatting
We should order from least granular to most, ie docker image -> docker container -> process -> endpoints

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #261

### CODE REVIEW

**Comment by paulbellamy** [comment]
It would be nice if the rankings were concentrated in one section of the file (or one datastructure), so it is easier to tell how they relate.

**Comment by paulbellamy** [comment]
There is code to gather bits and pieces, and generate the Tables, then there is code to organise them for display. They both feel very entwined together at the moment. But possibly separating them is a bigger refactor.

**Comment by paulbellamy** [comment]
But, other than that, it looks fine.

**Comment by tomwilkie** [comment]
Maybe make the numbers into constants?

**Comment by paulbellamy** [comment]
I was thinking something like:
```Go
var tableDefinitions := []struct{
    name string
    generator
    rank int
  }{
  {"table1", table1Func, 0},
}

for _, table :=  range tableDefinitions {
//...
}
```

But constants would be a smaller refactor, so that sounds fine.

**Comment by paulbellamy** [comment]
lgtm

**Pull request merged**
