### PR TITLE
Upgrade to go1.7

### PR DESCRIPTION
**Pull request by tomwilkie**
When the image exists...

### CODE REVIEW

**Comment by tomwilkie** [comment]
I had problems connecting the query service to nats in the service with this PR, so don't merge it yet.

**Comment by tomwilkie** [comment]
https://github.com/golang/go/issues/16739

**Comment by tomwilkie** [comment]
Why is that commit attributed to me? Weird...

Did you test a local deployment of the service @2opremio?

**Comment by 2opremio** [comment]
> Why is that commit attributed to me? Weird...

I amended your last commit instead of adding another one (happy to change the author if you want me to).

> Did you test a local deployment of the service @2opremio?

Tried to but couldn't, I am struggling in the transition to minikube

**Comment by tomwilkie** [comment]
> Tried to but couldn't, I am struggling in the transition to minikube

Okay before we commit this it will need to be tested locally, as go1.7 broke stuff pretty badly.

**Comment by 2opremio** [comment]
I can now launch the service after https://github.com/weaveworks/service-conf/pull/187 which lets me connect the browser and access the UI but I don't know how to connect a probe to minikube. Changing the loadbalancer type to NodePort gets me an IP from the docker network of the VM, which I cannot reach externally:

```patch
diff --git a/k8s/local/default/frontend-svc.yaml b/k8s/local/default/frontend-svc.yaml
index 3a0b04f..ff20c86 100644
--- a/k8s/local/default/frontend-svc.yaml
+++ b/k8s/local/default/frontend-svc.yaml
@@ -6,7 +6,7 @@ metadata:
   annotations:
     prometheus.io.port: "9145"
 spec:
-  type: LoadBalancer
+  type: NodePort
   ports:
     - port: 80
       name: http
```

```
$ kubectl describe svc frontend
Name:			frontend
Namespace:		default
Labels:			<none>
Selector:		name=frontend
Type:			NodePort
IP:			10.0.0.25
Port:			http	80/TCP
NodePort:		http	30184/TCP
Endpoints:		172.17.0.24:80
Port:			https	443/TCP
NodePort:		https	30997/TCP
Endpoints:		172.17.0.24:443
Session Affinity:	None
No events.

```

@ekimekim Have you successfully managed to connect an external probe to minikube?

**Comment by 2opremio** [comment]
OK, I have managed to test the service locally by launching a probe inside the minikube VM itself.

**Comment by 2opremio** [comment]
(the question to @ekimekim still stands though)

**Comment by tomwilkie** [comment]
LGTM

**Pull request merged**
