### PR TITLE
Don't log "expected" websocket errors

### LINKED ISSUE #1019: websocket: close error in logs
```
<app> INFO: 2016/02/24 10:16:53.200854 err: websocket: close 1001
<app> INFO: 2016/02/24 10:17:01.175204 err: websocket: close 1001
<app> INFO: 2016/02/24 10:17:11.121864 err: websocket: close 1005
```

### PR DESCRIPTION
**Pull request by paulbellamy**
Fixes #1019

Upgrading gorilla/websocket also makes the logging a bit nicer for the other errors.

### CODE REVIEW

**Comment by tomwilkie** [comment]
Do we also want this in app/controls.go:82 and app/pipes.go:44?

**Comment by paulbellamy** [comment]
We don't actually do anything with those errors, so...

**Comment by tomwilkie** [comment]
Can you look into:

```
<app> INFO: 2016/02/24 15:39:53.980948 err: websocket: close 1005 (no status)
<app> INFO: 2016/02/24 15:39:56.828722 err: websocket: close 1005 (no status)
<app> INFO: 2016/02/24 15:40:22.730329 err: websocket: close 1005 (no status)
<app> INFO: 2016/02/24 15:40:25.486719 err: websocket: close 1005 (no status)
<app> INFO: 2016/02/24 15:40:27.203276 err: websocket: close 1005 (no status)
```

Happens when you change topologies.

Otherwise LGTM.

**Comment by paulbellamy** [comment]
Turns out 1005 is also a valid websocket closing. It just means the other end sent a close frame with no reason specified.

**Pull request merged**
