### PR TITLE
Adjusted terminal character width/height estimation

### LINKED ISSUE #3178: Terminal window width wrong
The character window is about half the width of the UI window, and a little less tall.

Maybe because it's a Retina display?  But why wouldn't it be the same wrong in both dimensions?

image

### PR DESCRIPTION
**Pull request by fbarl**
Fixes #3178.

### CODE REVIEW

**Comment by dlespiau** [comment]
`character{Width,Height}` are only used if `wrapperNode.querySelector('.terminal .xterm-rows div');` doesn't return anything? does the selector need changing?

**Comment by fbarl** [comment]
@dlespiau Good catch! Since `v3`, `xtermj.js` is doing canvas rendering so we can't probe into DOM anymore (or at least not the same way). I suggest we simply get rid of that selector and keep only the constants.

p.s. in #3177 I'll try to enforce `Roboto Mono` font in terminal for all users so those constants won't be changing anymore with future updates.

**Comment by dlespiau** [comment]
Given the variety of screen DPIs and that those constants seem to be in pixels, the terminal size won't be correct almost everytime, no?

Instead of fixing the terminal width when creating the object, it seems like we my be able to leave the terminal occupy its natural allocation on the page and listen to the `resize` event, `term.on('resize', ....)` and send the resize commands on the `resize` callback.

**Comment by dlespiau** [comment]
Oh! there's a `fit` addon that would help here: https://xtermjs.org/docs/api/addons/fit/

Fit the terminal to a parent element and then query its size with `cols()` and `rows()`.

**Comment by fbarl** [comment]
Thanks for looking into it @dlespiau. I implemented your `fit` addon suggestion, feel free to take a look at the code and test it now :)

The code there is still pretty hacky, but hopefully now it's a bit more precise.

**Pull request merged**
