### PR TITLE
Dont shift canvas after it has been autoshifted

### LINKED ISSUE #496: Radial view bounces
bump bump

report: https://gist.github.com/2opremio/bf120582a99711b83c27

### PR DESCRIPTION
**Pull request by davkal**
Fixes #496

### CODE REVIEW

**Comment by 2opremio** [comment]
I've tested this and improves the situation (no more dancing), but now the nodes run away :)

please don't go

Even when you don't chase them:
don't go away from me

**Comment by davkal** [comment]
Can reproduce... :(

**Comment by davkal** [comment]
@2opremio please give it a whirl when you have the time

**Comment by 2opremio** [comment]
Good news: the dancing in the radial view seems to be gone

Bad news: Now I have difficulties repositioning the layout (I used to do that by dragging a container). In fact I run into some sort of graph "drag-teleportation" in which the nodes go away when I try to move them and after which all views are empty (container, host, image ...):

teleportation

I haven't been able to check whether zooming in and out still works since I am at home without a trackpad. Will try that on Monday.

**Comment by 2opremio** [comment]
It works beautifully now :) 

In fact scrolling zooms in and out now with my mouse at home (which means it was also working).

**Pull request merged**
