### PR TITLE
Importing lodash util functions explicitly

### PR DESCRIPTION
**Pull request by fbarl**
Also renamed `sortBy` variables/methods to `sortedBy` for:

* naming consistency with `sortedDesc` property
* avoiding the overlap with lodash `sortBy` function

### CODE REVIEW

**Comment by davkal** [comment]
Great!

Can we give https://www.npmjs.com/package/babel-plugin-lodash a try for the production config?

**Comment by foot** [comment]
Mmm, looks better!

I think these are quite different:

`import { sortBy } from 'lodash';`
`import sortBy from 'lodash/sortBy';`

The first needs the tree shaking to have an impact on build size.

**Comment by foot** [comment]
But it looks like the plugin davkal mentions sorts that out. Nice!

**Comment by foot** [comment]
Quick test of the UI main stuff seems to still be working too 👍 

LGTM

**Comment by fbarl** [comment]
@davkal PTAL, I added `babel-plugin-lodash` to `babel`, so I guess it should automatically be working for the production environment (I tested it locally and it works).

@foot Hopefully these kind of plugins will be redundant once we upgrade to Webpack 2 ;)

**Comment by davkal** [comment]
Like in the d3 upgrade, we need to remove lodash from the vendors bundle (otherwise it will be included wholesale).
```diff
diff --git a/client/webpack.local.config.js b/client/webpack.local.config.js
index 10294fb..caef570 100644
--- a/client/webpack.local.config.js
+++ b/client/webpack.local.config.js
@@ -36,7 +36,7 @@ module.exports = {
       './app/scripts/terminal-main',
       'webpack-hot-middleware/client'
     ],
-    vendors: ['babel-polyfill', 'classnames', 'dagre', 'filesize', 'immutable', 'lodash',
+    vendors: ['babel-polyfill', 'classnames', 'dagre', 'filesize', 'immutable',
       'moment', 'page', 'react', 'react-dom', 'react-motion', 'react-redux', 'redux',
       'redux-thunk', 'reqwest', 'xterm',
       'webpack-hot-middleware/client'
diff --git a/client/webpack.production.config.js b/client/webpack.production.config.js
index ae79087..027fda4 100644
--- a/client/webpack.production.config.js
+++ b/client/webpack.production.config.js
@@ -35,7 +35,7 @@ module.exports = {
     'terminal-app': './app/scripts/terminal-main',
     // keep only some in here, to make vendors and app bundles roughly same size
     vendors: ['babel-polyfill', 'classnames', 'immutable',
-      'lodash', 'react', 'react-dom', 'react-redux',
+      'react', 'react-dom', 'react-redux',
       'redux', 'redux-thunk']
   },
```

**Comment by davkal** [comment]
Otherwise LGTM

**Pull request merged**
