### PR TITLE
Highlight selected node

### PR DESCRIPTION
**Pull request by davkal**
Highlights selected nodes like in Cello, with a circular layout of the adjacent nodes and a fade out of the non-adjacent nodes.

screen shot 2015-09-09 at 18 27 49

### CODE REVIEW

**Comment by davkal** [comment]
This is based on PR #445 and will fix #324

**Comment by peterbourgon** [comment]
Brilliant. Basically this only works when the detail pane is up, correct?

**Comment by davkal** [comment]
Correct. It will revert to the old layout when you close it.

**Comment by peterbourgon** [comment]
Looks great. One thing: when you click on a node, the canvas stays fixed, so some of the adjacent nodes can get moved to annoying places, like just offscreen, under the detail pane, or into (underneath) the menu bar at the top. If that could be avoided, would be nice.

**Comment by davkal** [comment]
Please have another look.

**Comment by peterbourgon** [comment]
Ah, works great! Nice job. :+1:

**Comment by peterbourgon** [comment]
Can we get a merge?

**Pull request merged**
