### PR TITLE
run shfmt and shellcheck on shell scripts

### PR DESCRIPTION
**Pull request by paulbellamy**

### CODE REVIEW

**Comment by 2opremio** [comment]
LGTM, provided green and that https://github.com/weaveworks/build-tools/pull/44 is included (github doesn't seem to show contents of git-tree updates)

**Comment by 2opremio** [comment]
@paulbellamy Are you still working on this or you gave up? :)

**Comment by paulbellamy** [comment]
Sidetracked on other things.

**Comment by 2opremio** [comment]
@paulbellamy Still planning to work on this?

**Comment by paulbellamy** [comment]
No

**Pull request closed without merging**
