### PR TITLE
Cola layout

### PR DESCRIPTION
**Pull request by peterbourgon**
@davkal any reason we shouldn't merge this?

### CODE REVIEW

**Comment by davkal** [comment]
@peterbourgon breaks chrome with this report by @tomwilkie : https://gist.github.com/davkal/5e40f7455d87b86dbc87

**Comment by davkal** [comment]
I need to debug this.

**Comment by davkal** [comment]
Cola produces some very clean layouts, but jumps all the time

screen shot 2015-08-24 at 19 50 58

This is based on Tom's setup.

**Comment by tomwilkie** [comment]
Oh yes that does look better.  Anyway we can stop it jumping?  Have you tried the same trick?

**Comment by davkal** [comment]
Will try the reuse trick tomorrow

**Comment by davkal** [comment]
The reuse trick doesnt even though I cache node positions and then feed them back :( maybe some randomizer in the constraints engine works against us, I'll dig a bit through the code.

**Comment by davkal** [comment]
Just verified, that the topology is always the same, it's still jumpy.

**Comment by davkal** [comment]
I'm migrating the node management to ImmutableJS objects, so that it will be easier to compare updated topologies and see if they need re-rendering.

**Comment by davkal** [comment]
Fixing tests...

**Comment by davkal** [comment]
Internet is now on top, and they are nicer spaced. Switching back and forth between topos is still a bit unpredictable

screen shot 2015-08-27 at 17 45 20

**Comment by tomwilkie** [comment]
I'm not too worries about switching-back-and-forth, its more when staying on the same topology, and the graph changes, do it completely re-layout the page?

**Comment by tomwilkie** [comment]
Also that layout really highlights the need to do better with the internet node: all but one of those connections if going out to the internet, and one is coming in.  Confusing...

**Comment by davkal** [comment]
Same topo, but a node get added/removed, then the layout similarity between renders depends how connected the node was. But we can smooth this out be adding an animation so nodes travel instead of jump.

**Comment by davkal** [comment]
Agreed with the directionality, it's weird now with hovering over nodes, because some nodes seem connected, but dont highlight their peer because it's an ingress link.

**Comment by davkal** [comment]
Closing this, dagre wins out.

**Pull request closed without merging**
