### PR TITLE
Fix help menu not opening from 'search' hint

### PR DESCRIPTION
**Pull request by jpellizzari**
Fix for #2227 

Fixes the issue where the help menu wasn't opening unless there was text in the field. Also changed the debug menu icon to a 'warning' icon (the bug didn't make sense anymore).

### CODE REVIEW

**Comment by jpellizzari** [comment]
@bowenli Could you review pls?

**Comment by bowenli** [comment]
I'm earmarking the caution icon for this: https://github.com/weaveworks/scope/issues/2139 so let's keep the bug for now.

**Comment by bowenli** [comment]
Pls squash commits

**Comment by jpellizzari** [comment]
Each of those is a separate change that is unrelated to the others. I would like to keep those commits so that they can be rolled back individual if necessary.

**Comment by jpellizzari** [comment]
Removed the icon change

**Comment by bowenli** [comment]
lgtm. your circleci is failing though.

**Comment by jpellizzari** [comment]
Master be broken.

**Pull request merged**
