### PR TITLE
k8s: Use service account token by default and improve error logging

### LINKED ISSUE #717: See if scope k8s client can access the api server from inside a pod using service account
May have issues as it's in the host namespace

### PR DESCRIPTION
**Pull request by 2opremio**
Fixes #717 

@paulbellamy PTAL

### CODE REVIEW

**Comment by tomwilkie** [comment]
This will need updates to README to document how to use scope with k8s.

**Comment by paulbellamy** [comment]
LGTM, and needs documentation.

**Comment by 2opremio** [comment]
> This will need updates to README to document how to use scope with k8s.

I discussed this with @paulbellamy but we were not sure we should modify the documentation until we release it. The README exhorts the user to install the latest release, so documenting something we haven't released is going to be misleading.

**Comment by tomwilkie** [comment]
Thats fine, but lets at least have the update ready before merging this.  We'll have to do the whole next-release-readme branch thing.

**Comment by 2opremio** [comment]
Sure, I will create a separate branch with the updates. Let me do it before we merge this so that it can be reviewed together with this PR.

**Comment by 2opremio** [comment]
@tomwilkie @paulbellamy I've included the documentation here after all since the users should simply use the new resource definitions at https://github.com/TheNewNormal/kube-charts/tree/master/weavescope/manifests

That should basically be the source of truth of how to use the flags which I will update once we release 0.12 with this PR.

**Comment by 2opremio** [comment]
CC @rimusz  please have a look at the documentation update. 

I really like Helm but due to the extra manual steps involved I am not completely sure it contributes to make the installation easier. The steps to install Helm and to add the extra repo probably don't pay off, since the user needs to invoke kubectl manually anyways (due to the optional app component and the deployment ordering restriction, which I believe cannot be enforced though `helm install`)

Please let me know if I missed something and `helm install` could be used in our usecase. Thanks.

**Comment by rimusz** [comment]
@2opremio I said in the email I will make a PR to upstream Helm repo, so these steps will be redundant:
```
3. Add the kube-charts helm repo:
 
 helm up
 helm repo add kube-charts https://github.com/TheNewNormal/kube-charts
 helm up
```
Also using new helm v0.3 (template and generator options) should be possible to make scope install much easier with different requirements

**Comment by 2opremio** [comment]
@rimusz Good! Is there a possibility to define a deployment order and optional resources for `helm install`?

 Without this we need to resort to use `kubectl` manually and `helm` ends up being used merely as a glorified `curl`.

**Comment by paulbellamy** [comment]
The manifests look fantastic but, due to all the manual fiddling still needed, I'm not sure helm adds much yet. Let's see what the instructions look like without it, @2opremio?

**Comment by 2opremio** [comment]
I agree, we can include Helm again once:
* The chart in merged upstream (no need for `helm add repo`)
* Helm v0.3 is released (which may allow automating the customization of the probe arguments)
* `helm install` supports setting a deployment order and optional resources.

**Comment by 2opremio** [comment]
@rimusz Please let us know if you are OK with us using the resource definitions without Helm until the problems I outlined above are resolved. 

Otherwise we are happy leaving the documentation as it was until they are resolved and we include Helm in the instructions.

**Comment by rimusz** [comment]
@2opremio sure, that's fine

**Pull request merged**
