### PR TITLE
Document how to obtain profiles without `go tool pprof`

### PR DESCRIPTION
**Pull request by 2opremio**
Improves #983

### CODE REVIEW

**Comment by tomwilkie** [comment]
Can we roll this into a command on the scope script?

**Comment by 2opremio** [comment]
Not as-is. The probe needs to run with `--probe.http.listen 4041`. This is just a temporary solution until we properly implement a command for it (dumping a symbolized profile and all ...)

**Comment by tomwilkie** [comment]
I have no qualms about always running the probe on :4041 if it makes this easier.

**Comment by 2opremio** [comment]
Sure, but when we automatize it, I'd rather do it properly (i.e. not obtaining a unsymbolized profile). My intention is to document this until somebody gets around to do it and I am working on other stuff right now.

**Comment by 2opremio** [comment]
Maybe it would be better to suggest using a go container instead of curl ...

**Comment by 2opremio** [comment]
@tomwilkie I have updated the PR to use containerized-go instead of curl, which is way simpler. PTAL

**Comment by 2opremio** [comment]
@tomwilkie mentioned it was OK to merge offline

**Pull request merged**
