### PR TITLE
Release 0.17.1

### PR DESCRIPTION
**Pull request by 2opremio**

### CODE REVIEW

**Comment by jml** [comment]
Things to test before a release, not currently covered by our integration tests:

- [ ] Start a 2 node cluster and leave a UI connected, watch for performance regression
- [ ] Run a Scope cluster on ECS
- [ ] Run Scope on https://github.com/microservices-demo/microservices-demo/
- [ ] Start and stop Scope in standalone mode
  - [ ] Linux
  - [ ] docker-machine
- [ ] Deploy & verify on Weave Cloud
  - [ ] Controls appear for containers and function correctly
  - [ ] Local scope in probe-only mode connects to Weave Cloud and renders correctly
  - [ ] No new errors in logging or telemetry

## Things to think about

- Kubernetes Integration
- CPU and memory usage

**Comment by jml** [comment]
On Slack, @2opremio asked a bunch of us to test the release. Current process is very ad hoc, with lots of duplication of effort.

Above is a copy of the current checklist: https://github.com/weaveworks/scope/wiki/Release-Qualification. We can check these off as we've tested them as a step toward doing less work when validating releases.

**Comment by jml** [comment]
Things I don't understand from the checklist:

> - [ ] Start a 2 node cluster and leave a UI connected, watch for performance regression

* What counts as a performance regression?
* How do I start a two node cluster?

> - [ ] Run a Scope cluster on ECS

* How do I do this?

> - [ ] Run Scope on https://github.com/microservices-demo/microservices-demo/

* What steps do I need to follow for this?

> - [ ] Deploy & verify on Weave Cloud

* How can I tell how the version on Weave Cloud relates to the release candidate?

**Comment by 2opremio** [comment]
@jml I am not sure this is the right forum for discussing fully fledged release testing since this is just a patch release.

**Comment by jml** [comment]
OK, then I'm done testing.

**Comment by 2opremio** [comment]
> OK. Then please say what kind of testing you want.

The release makes changes with respect to:
* Creating the kubernetes client
* Stopping docker for mac
* Rendering

So testing anything involving those three, together with a general end to end test would help.

**Comment by 2opremio** [comment]
@jml Let's continue the discussion about release testing on https://github.com/weaveworks/scope/issues/1677#issuecomment-240982871

**Comment by jml** [comment]
* I don't know what creating the kubernetes client means
* Stopping on docker for Mac works for me
* I did not observe any rendering bugs
* I connected to frontend.dev.weave.works with no errors observed

LGTM.

**Comment by 2opremio** [comment]
Thanks @jml 

> I don't know what creating the kubernetes client means

I meant, when the probe creates the kubernetes client to connect to the API server.

**Pull request merged**
