### PR TITLE
launcher script: Fix inconsistent whitespace

### PR DESCRIPTION
**Pull request by ekimekim**
Spotted this while reading through some bits and pieces for understanding.

### CODE REVIEW

**Comment by jml** [comment]
LGTM.

Please merge after tests pass.

**Comment by tomwilkie** [comment]
@ekimekim would be good to make the linter script catch this in the future.

**Comment by jml** [comment]
And also to have the linter actually run on scope shellscript code :)

**Comment by ekimekim** [comment]
+1, will do. good exercise to understand our linting, and to a lesser
extent our CI

**Pull request merged**
