### PR TITLE
Aarch64 support

### PR DESCRIPTION
**Pull request by adivjoseph**
Tested on Odroid-C2 Ubuntu 16.04, OD1000 Ubuntu 17.04 and MacchiatoBin Ubuntu 16.04. Test application Weaveworks Socks portal.

### CODE REVIEW

**Comment by rade** [comment]
We've been through all this with Weave Net. See the [makefile](https://github.com/weaveworks/weave/blob/master/Makefile). That is neater and also adds manifests, which are missing from this PR.

**Comment by adivjoseph** [comment]
I like the template method, i will rework the PR. Also I will use the Docker distrib model.

**Comment by 2opremio** [comment]
Fantastic, thanks!

**Comment by adivjoseph** [comment]
I have made an updated PR that does not require the proliferation of Dockerfiles.
Hence this PR is being removed. Thanks for the good feedback.

**Pull request closed without merging**
