### PR TITLE
Highlight a single unconnected node on hover.

### LINKED ISSUE #787: Nodes w/out edges don't have a blue hover glow.
Feels broken without it.

### PR DESCRIPTION
**Pull request by foot**
Wasn't happening before.

Fixes #787

### CODE REVIEW

**Comment by tomwilkie** [comment]
@foot Need rebasing on master for circle to pass.

**Comment by davkal** [comment]
LGTM (still need rebase?)

**Comment by tomwilkie** [comment]
I think Simon already rebased (the test passed)

**Comment by foot** [comment]
I rebased 9 days ago, could do w/ another one.

**Pull request merged**
