### PR TITLE
Release 1.5.0

### PR DESCRIPTION
**Pull request by 2opremio**
@rndstr @fbarl @davkal @foot @ekimekim @bowenli @jpellizzari @abuehrle @pidster @errordeveloper @rade Please chip in by testing this release branch in the scenarios below and tick off what you tested afterwards (including your name at the end). Have a look at the CHANGELOG to prioritize your testing.

To make things easier to test I have pushed the image `weaveworks/scope:release-1.5-1667984`:

- [ ] Start a 2 node cluster and leave a UI connected, watch for performance regression
- [ ] Run a Scope cluster on ECS
- [x] Run Scope on https://github.com/microservices-demo/microservices-demo/
- [x] Run Scope on Docker For Mac
- [x] Start and stop Scope in standalone mode
  - [x] Linux
  - [ ] docker-machine
- [x] Connect probes from release candidate to Weave Cloud
  - [x] Local scope in probe-only mode connects to Weave Cloud and renders correctly
    - [x] dev
    - [x] prod
  - [x] Controls appear for containers and function correctly
    - [x] dev
    - [x] prod
  - [x] No new errors in logging or telemetry
    - [x] dev
    - [x] prod
- [ ] UI integration
  - [x] Hot-reloading `cd client && npm i && npm start` and open http://localhost:4042
  - [x] UI under prefix path  `cd client && npm run build && npm start-production` and open http://localhost:4043/scoped/
  - [ ] URL parameters: Run previous release and click around, keep UI open, start new release, reload page
- [x] UI features
  (To test: clone [microservices demo](https://github.com/microservices-demo/microservices-demo) and run `cd deploy/docker-compose && docker-compose up`)
  - [x] General: switch between topologies, see nodes and edges, details panel
  - [x] Zoom and pan, switch between topologies
  - [x] Topology filters: namespaces, system containers, etc.
  - [x] Metrics on canvas, try pinning/unpinning
  - [x] Search
    - [x] by container name
    - [x] by usage `cpu < 2%`
  - [x] Terminal
    - [x] Attach to container to see logs
    - [x] Exec to container and type `ls`
    - [x] Pop out terminal
  - [x] Contrast mode
  - [x] Download report
  - [x] Pause button

## Things to think about
- ECS Integration
- Kubernetes Integration
- CPU and memory usage

### CODE REVIEW

**Comment by abuehrle** [comment]
In the container view switching between DNS and Image retains the "nothing to show" watermark even though there is an app running.  #2592

**Comment by abuehrle** [comment]
Filtering by stopped vs running is reversed in container --> DNS view #2594

**Comment by abuehrle** [comment]
popping out terminal and going full screen doesn't allow you to close the terminal again, as the controls are hidden (goes beyond your desktop). #2595

**Comment by fbarl** [comment]
Pause button not appearing because it's part of a feature-flagged Time Travel component. https://github.com/weaveworks/scope/pull/2585 moves it back to the footer (temporarily).

**Comment by abuehrle** [comment]
**Force re-layout** not working #2596

**Comment by abuehrle** [comment]
**Weave Cloud**: High contrast mode not appearing #2598

**Comment by rndstr** [comment]
should the `client/package.json` version be bumped as part of this release?

**Comment by abuehrle** [comment]
Memory CPU filter missing from Containers in WC: 

https://github.com/weaveworks/service-ui/issues/625

**Comment by abuehrle** [comment]
Searching for Scope not appearing in Graph mode: 

https://github.com/weaveworks/service-ui/issues/628

**Comment by abuehrle** [comment]
Scope containers not appearing in Containers view: #2601

**Comment by 2opremio** [comment]
I think we are good to do. There are still some issues but I don't think they are blockers.

Please let me know if you think otherwise. I will create a release in the coming hours if I don't hear anything.

**Comment by fbarl** [comment]
> I think we are good to do. There are still some issues but I don't think they are blockers.

I think the only thing that could qualify as a blocker would be #2603 - I guess it would also be good to know if it was introduced after or before the `1.4.0` release.

**Comment by 2opremio** [comment]
I will confirm

**Comment by 2opremio** [comment]
It was already broken in 1.4.0 , so I will just cut the release.

**Pull request merged**
