### PR TITLE
Omit controls field from json if emtpy.

### LINKED ISSUE #654: Controls should be omitted from report if empty
They're being held by the timestamp:
```json
"controls": {
  "timestamp": "0001-01-01T00:00:00Z"
}
```

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #654

### CODE REVIEW

**Comment by paulbellamy** [comment]
They're still there. Due to go's awkward zero semantics, you have to explicitly render the timestamp as in: https://github.com/weaveworks/scope/blob/master/report/metrics.go#L215

**Comment by tomwilkie** [comment]
Definitely not there (on topologies) any more:

screen shot 2015-12-04 at 12 27 24

**Comment by tomwilkie** [comment]
So I guess you mean on Nodes; let me take a look.

**Comment by paulbellamy** [comment]
LGTM

**Pull request merged**
