### PR TITLE
Show a spinner while node details are loading

### PR DESCRIPTION
**Pull request by davkal**
screen shot 2015-11-20 at 16 51 12

### CODE REVIEW

**Comment by 2opremio** [comment]
I am getting the spinner but the details pane color is not matching the node's color. Wasn't that fixed?

screen shot 2015-11-24 at 4 48 34 pm


Also, as you show in your screenshot, the details panel is grey while showing the spinner. Why aren't you showing the final color? Is there a technical limitation preventing you from doing that?

**Comment by davkal** [comment]
The color matching was done in a concurrent PR so it's broken in this one, but was now merged to master in #689 and #690.

But already coloring the panel in the final color is a good idea. will do that.

**Comment by 2opremio** [comment]
cool

**Comment by davkal** [comment]
@2opremio PTAL.

**Comment by 2opremio** [comment]
@davkal LGTM, however, I've noticed that if you click on nodes while they are in the background, their detail requests end up somehow queuing (?) and displaying when you are no longer interested.

queued events

**Comment by davkal** [comment]
You are right, when clicked, the details panel should go back to Loading mode.

**Comment by 2opremio** [comment]
Will test this tomorrow. Why are tests failing BTW?

**Comment by 2opremio** [comment]
Edge test ...

**Comment by davkal** [comment]
yeah, unrelated.

**Comment by 2opremio** [comment]
It still suffers from the *problem* I mentioned, this video makes it more clear (wait until the end):

**Comment by davkal** [comment]
Ah now I know what u mean. Will see how/if this can be fixed.

**Comment by 2opremio** [comment]
Much better now, although the details pane takes longer to load (it could be that my system is slower today due to the number of containers) and the Internet node for some reason is brown while it loads (although it's final color is purple):

Wrong internet details pane color while loading

**Comment by 2opremio** [comment]
LGTM

**Pull request merged**
