### PR TITLE
Disable deployments and replica sets if k8s is 1.1

### LINKED ISSUE #1452: ReplicaSet/Deployment errors on kubernetes 1.1
We should probably check if ReplicaSets are available instead of spamming the logs.
```
<probe> ERRO: 2016/05/09 14:12:24.908539 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:105: Failed to list *extensions.Deployment: the server could not find the requested resource
<probe> ERRO: 2016/05/09 14:12:35.006439 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:105: Failed to list *extensions.Deployment: the server could not find the requested resource
<probe> ERRO: 2016/05/09 14:12:35.007778 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:105: Failed to list *extensions.ReplicaSet: the server could not find the requested resource
<probe> ERRO: 2016/05/09 14:12:45.051527 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:105: Failed to list *extensions.ReplicaSet: the server could not find the requested resource
<probe> ERRO: 2016/05/09 14:12:45.052965 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:105: Failed to list *extensions.Deployment: the server could not find the requested resource
<probe> ERRO: 2016/05/09 14:12:55.087494 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:105: Failed to list *extensions.ReplicaSet: the server could not find the requested resource
<probe> ERRO: 2016/05/09 14:12:55.087674 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:105: Failed to list *extensions.Deployment: the server could not find the requested resource
<probe> ERRO: 2016/05/09 14:13:05.116282 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:105: Failed to list *extensions.Deployment: the server could not find the requested resource
<probe> ERRO: 2016/05/09 14:13:05.116594 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:105: Failed to list *extensions.ReplicaSet: the server could not find the requested resource
<probe> ERRO: 2016/05/09 14:13:15.186622 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:105: Failed to list *extensions.Deployment: the server could not find the requested resource
<probe> ERRO: 2016/05/09 14:13:15.187331 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:105: Failed to list *extensions.ReplicaSet: the server could not find the requested resource
```

### PR DESCRIPTION
**Pull request by paulbellamy**
Fixes #1452

### CODE REVIEW

**Comment by tomwilkie** [comment]
LGTM

**Comment by paulbellamy** [comment]
Looks good, but doesn't seem to *actually* work. Maybe 1.1 is saying it supports extensions/v1beta1, even though it doesn't...

**Comment by paulbellamy** [comment]
Yep. 1.1 says it supports extensions/v1beta1, which it does. Just.. differently..

**Comment by 2opremio** [comment]
LGTM

**Pull request merged**
