### PR TITLE
Refactor out the docker process mapper for use in tracer.

### PR DESCRIPTION
**Pull request by tomwilkie**

### CODE REVIEW

**Comment by peterbourgon** [comment]
This will conflict annoyingly with #123 :\

**Comment by tomwilkie** [comment]
Okay let me handle that; we'll get #123 in first.

We have to avoid doing such large PRs in the future.

**Comment by tomwilkie** [comment]
This depends on #178

**Comment by tomwilkie** [comment]
Now #178 is in, this change is much smaller.  @peterbourgon mind taking another look?

**Comment by peterbourgon** [comment]
LGTM. We should start testing with the race detector.

**Pull request merged**
