### PR TITLE
New sidebar in the bottom left

### LINKED ISSUE #207: Add a status bar to show topology statistics
When we start showing containers without connections, we'll want an option to not do that.

Also means we could start probing for processes without connections, and optionally show/hide them.

### PR DESCRIPTION
**Pull request by davkal**
* status bar (fixes #207)
* moved error reporting down to statusbar, error is shown in status field
* moved topology options to sidebar
* render topology option like snackbar
* option items stack on top
* upgrade material-ui to 0.11

### CODE REVIEW

**Comment by davkal** [comment]
screen shot 2015-09-14 at 20 47 48

**Comment by davkal** [comment]
Gotta change the wording now to reflect current state, not the action. Eg. "Showing system containers".

**Comment by davkal** [comment]
screen shot 2015-09-14 at 20 55 02

**Comment by tomwilkie** [comment]
Nice.  I'd like to include in the status bar how many nodes were filtered out (to make it clear when you see a blank page that scope is working).

**Comment by davkal** [comment]
@tomwilkie yeah, could you add this to the stats object? Then I can render it.

**Pull request merged**
