### PR TITLE
Enable and fixup linting on client test js

### LINKED ISSUE #632: We should lint test js

### PR DESCRIPTION
**Pull request by paulbellamy**
Fixes #632 

@davkal There is one left I'm not sure how to resolve:
```
app/scripts/stores/__tests__/app-store-test.js
  75:8  error  ClickGroupingAction is defined but never used  no-unused-vars
```

Is this a missing test, or should we just remove it?

### CODE REVIEW

**Comment by davkal** [comment]
@paulbellamy this was old functionality, can be removed.

**Comment by paulbellamy** [comment]
Bah, jest globally injects a bunch of stuff, and eslint doesn't have a way to ignore it in test files. We can either ignore jest stuff everywhere, or have two npm scripts (and run both).

**Comment by paulbellamy** [comment]
Currently throwing: `Error: ENOENT, no such file or directory 'app/**/*-test.js'`

**Comment by davkal** [comment]
I've added test linting and upgrade linter as part of #649. All green.

**Pull request closed without merging**
