### PR TITLE
Release 0.12.0

### PR DESCRIPTION
**Pull request by tomwilkie**

### CODE REVIEW

**Comment by tomwilkie** [comment]
I'm LGTM on this release @paulbellamy.  Blog post ready to go http://www.weave.works/wp-admin/post.php?post=2462

**Comment by 2opremio** [comment]
I did some QA on ECS and found:

* #868 not a regression and not a blocker.
* #869 a bit scary but I recall seeing it in one occasion while demoing an earlier version, so I don't think it's a regression.
* #870 not a blocker but maybe easy to fix?

**Comment by 2opremio** [comment]
I've also found https://github.com/weaveworks/scope/issues/871 (definitely not a blocker).

**Comment by tomwilkie** [comment]
#870 is fixed.  Release is good to go from my PoV.  If I get a chance I'll build the release artefacts.

**Comment by 2opremio** [comment]
I have found #881 this morning which is a blocker. I will work on getting more information.

**Comment by 2opremio** [comment]
I've also managed to reproduce the high CPU in the App I observed yesterday, which is another blocker: #854

**Pull request merged**
