### PR TITLE
Fix a couple bugs in metrics first/last calculation

### LINKED ISSUE #653: Container CPU usage sparkline not rendering correctly
These are against an alpine container running `/bin/sh`

There are a couple issues:

- `first` and `last` json fields are included even if the timestamp is "zero".
- `first` on the cpu graphs is always zero.

### PR DESCRIPTION
**Pull request by paulbellamy**
Fixes #653

### CODE REVIEW

**Comment by tomwilkie** [comment]
LGTM (assuming its green)

Why is the change to the intermediate marshalling necessary?  Is it for the UI? A couple of lines in the PR would be nice :-)

**Comment by paulbellamy** [comment]
Ah, fair enough. In the js, since it's harder to check for go's `time.Time{}` value, we check the existence of a first field. So if it is zero we want to omit it, to stop rendering sparklines of all time.

**Comment by paulbellamy** [comment]
The first/last calculation bug was resulting in `first(time.Now(), time.Time{})` returning `time.Time{}`. Which led to merge being non-commutative.

**Comment by tomwilkie** [comment]
Thanks!

**Pull request merged**
