### PR TITLE
Release 0.15.0

### PR DESCRIPTION
**Pull request by 2opremio**

### CODE REVIEW

**Comment by tomwilkie** [comment]
Once #1503 is merged, LGTM from me.

**Comment by paulbellamy** [comment]
LGTM

**Comment by davkal** [comment]
LGTM 🚀

**Comment by 2opremio** [comment]
LGTM. https://github.com/weaveworks/scope/issues/897 isn't fixed though (which I am not too happy about), so I have moved it to pre-1.0

**Pull request merged**
