### PR TITLE
Keep the resource metric pinned on mouse out

### LINKED ISSUE #2397: Pinned metric temporarily not displayed on mouse leave
no-pinned

Introduced by #2296 (currently only on dev).

### PR DESCRIPTION
**Pull request by fbarl**
Fixes #2397.

### CODE REVIEW

**Comment by foot** [comment]
I think this logic is encapsulated in https://github.com/weaveworks/scope/blob/master/client/app/scripts/components/metric-selector.js#L16 but I'm not sure why its not working there.

Still getting an env going...

**Comment by fbarl** [comment]
Good catch @foot, let me look into it

**Comment by foot** [comment]
Oh! Perhaps `props.pinnedMetric` is not being passed in.

**Comment by foot** [comment]
LGTM

**Pull request merged**
