### PR TITLE
Customizable Container Label Filters

### PR DESCRIPTION
**Pull request by CarltonSemple**
I added a function that loads container filters from the CONTAINER_FILTERS environment variable. So rather than just having "system" and "application" as filter options, a potential user can easily add more filters by adding to the environment variable in the Dockerfile

### CODE REVIEW

**Comment by 2opremio** [comment]
@CarltonSemple Thanks for the patch. I haven't had a look at it yet but, for starters. Could you please:

* run `make lint` locally and fix the problems it prints.
* Squash the commits into a single change.

**Comment by CarltonSemple** [comment]
@2opremio Sorry for the delay. I ran `make lint`, but a lot of the errors I see so far seem to be coming from files I didn't touch. Am I doing this correctly?

screen shot 2016-09-22 at 3 53 36 pm

**Comment by rade** [comment]
@CarltonSemple don't worry about the lint errors in the tests; the `api_topologies.go` one is what needs fixing.

 @2opremio I suspect the linter on CircleCI doesn't run on test code, for some reason. AFAICT all the complaints in the tests were introduced in 8a950a59d.

**Comment by CarltonSemple** [comment]
I messed up the commits, so I'm just going to make a new pull request

**Comment by 2opremio** [comment]
@CarltonSemple You don't have to create a new pull request, simply force-push once you've made the changes you want.

**Comment by CarltonSemple** [comment]
ohh..

**Pull request closed without merging**
