### PR TITLE
Update to go 1.6.1

### PR DESCRIPTION
**Pull request by tomwilkie**
See https://groups.google.com/forum/#!msg/golang-announce/9eqIHqaWvck/kXsfO0ogLAAJ

I don't think we're affected, but might as well do it.

### CODE REVIEW

**Comment by 2opremio** [comment]
I would merge this after 0.14 (just in case)

**Comment by peterbourgon** [comment]
re: stripping, are we positive this isn't going to negatively affect us in the future? Put another way: why don't they have this on by default?

**Comment by paulbellamy** [comment]
Seems fine. if we fine we're missing the gdb debugging, then we could parameterize it `make DEBUG=true`, or roll it back.

**Comment by tomwilkie** [comment]
+1 lets try it and roll it back if it causes problems.

**Comment by 2opremio** [comment]
Has anybody checked whether 'go tool pprof' works without the symbols? If it doesn't we should revert it.

**Pull request merged**
