### PR TITLE
Filter nodes that are only connected to themselves.

### LINKED ISSUE #656: A node with only connections to itself should count as "unconnected"
screen shot 2015-11-12 at 13 33 37

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #656

### CODE REVIEW

**Comment by davkal** [comment]
It works. But then there is no options to show unconnected nodes. The option has no action. I think if we filter nodes we should allow to unset the filter.

screen shot 2015-12-01 at 15 58 30

**Comment by tomwilkie** [comment]
This is on the Applications view?  We decide a while back not to add a filter for that as there would be too many processes in the show-unconnected state.  Either way, do you mind filing a separate issue for this?   With the recent improvements in the rendering engine this is something we could revisit.

**Comment by davkal** [comment]
Added #713 for the missing option. Otherwise LGTM

**Comment by tomwilkie** [comment]
Thanks!

**Pull request merged**
