### PR TITLE
Print DNS errors

### LINKED ISSUE #1577: Scope probe fails to report to some of the target apps
When mirroring scope reports from dev to the new dev-ka cluster, I noticed that two hosts were missing.

Inspecting the logs of the two host probes show evidence of publishing to frontend.dev-ka.weave.works:80 not starting at all (there are no lines like `Publish loop for [DevKAIP]:80 starting` are present in the logs)

logs: https://gist.github.com/2opremio/5d9335c84bf9f2929acd54df1cc173af

goroutine dump: https://gist.github.com/2opremio/5d9335c84bf9f2929acd54df1cc173af#file-logs-txt-L2129

### PR DESCRIPTION
**Pull request by 2opremio**
Fixes #1577

### CODE REVIEW

**Comment by tomwilkie** [comment]
By default we try and resolve scope.weave.local, which will fail if people aren't running weave (most aren't), so this will pollute the logs, no?

**Comment by 2opremio** [comment]
> By default we try and resolve scope.weave.local, which will fail if people aren't running weave (most aren't), so this will pollute the logs, no?

True, it's similar to https://github.com/weaveworks/scope/issues/1599#issuecomment-226777072 but I don't think the solution is to remove all errors, including legitimate ones.

How about only including the `scope.weave.local` target once weave is found?

**Comment by tomwilkie** [comment]
> How about only including the scope.weave.local target once weave is found?

I don't like the hardcoding - how about we only report resolution errors once (or n times) per target and silence them after?  And similarly, when the start succeeding again, we log something.

**Comment by 2opremio** [comment]
> I don't like the hardcoding

It's not hardcoding, I wrote `scope.weave.local` to continue the conversation but we will use whatever is provided as `--probe.weave.hostname`

It makes sense, if weave is not running, why are we even targeting that host?

> how about we only report resolution errors once (or n times) per target and silence them after? And similarly, when the start succeeding again, we log something.

That's an option too, but I prefer the former because it won't display irrelevant errors

**Comment by tomwilkie** [comment]
> It makes sense, if weave is not running, why are we even targeting that host?

We don't know if we are running weave or not.  We assume we are, and try to use it.

I think you're suggesting we only log errors after we have successfully resolved a host?  But you are also arguing we should show resolution errors?  Or would you just do this as a special case for resolution of scope's weavedns hostname?

I think it too special cased, and a more general rule (like only logging the first error) would be easier to understand.

**Comment by 2opremio** [comment]
> We don't know if we are running weave or not. We assume we are, and try to use it.
>
> I think you're suggesting we only log errors after we have successfully resolved a host? But you are also arguing we should show resolution errors? Or would you just do this as a special case for resolution of scope's weavedns hostname?

What I am suggesting is we only register the weave target in the probes after we have proof of weave working (e.g. after `weave ps` succeeds or the `weave status` request suceeds ...)


> I think it too special cased, and a more general rule (like only logging the first error) would be easier to understand.

We can do both. Only log the first error and only target WeaveDNS target once we know weave is successfully running.

**Comment by tomwilkie** [comment]
LGTM; I see we only get/set from the single goroutine - does it matter that we create the map on a different one?

**Comment by 2opremio** [comment]
> does it matter that we create the map on a different one?

Not AFAIK

**Pull request merged**
