### PR TITLE
update some javascript dependencies

### PR DESCRIPTION
**Pull request by dholbach**

### CODE REVIEW

**Comment by qiell** [comment]
Screenshot from 2019-08-21 16-55-58


Not able to drag the components in Graph Mode, getting above error in Console of UI.

**Comment by qiell** [comment]
It occurs when multiple versions of d3-selection are listed in yarn.lock https://stackoverflow.com/a/53478226/6948058
https://github.com/d3/d3-selection/issues/185#issuecomment-419474845

cc: @fbarl

**Comment by dholbach** [comment]
> It occurs when multiple versions of d3-selection are listed in yarn.lock https://stackoverflow.com/a/53478226/6948058
> [d3/d3-selection#185 (comment)](https://github.com/d3/d3-selection/issues/185#issuecomment-419474845)

Wow, nice catch!

Reverting `d3-selection` to `1.3.2` fixes the issue.

**Comment by qiell** [comment]
We can fix it by adding the `resolutions` section in `package.json` file. I got the solution from https://github.com/d3/d3-selection/issues/185#issuecomment-488386336

```diff
+  "resolutions": {
+    "d3-selection": "1.3.2",
+    "d3-selection": "1.4.0"
+  },
```
>  "d3-selection": "1.3.2" is required in resolutions because it is used in [ui-components](https://github.com/weaveworks/ui-components/blob/b151cc1cec5f5b9589963241987cb96af292b010/package.json#L64)

I tried it on my local setup and it works fine.

**Comment by dholbach** [comment]
Maybe we can merge as is and then update the rest in another PR?

**Comment by qiell** [comment]
Sure @dholbach

**Pull request merged**
