### PR TITLE
CI build speed-ups

### PR DESCRIPTION
**Pull request by bboreham**
This takes it down to around 20 minutes, although scope is currently running with 3 "containers".

Ref #2271

### CODE REVIEW

**Comment by bboreham** [comment]
Netlify failure is caused by me bumping the Ruby version; it needs an associated change in the Netlify box
https://github.com/weaveworks/website-next/issues/173

**Comment by rade** [comment]
Is there anything left to do here?

**Comment by bboreham** [comment]
The changes in the tools directory need to be done in the build-tools repo. 
The Netlify build needs to be updated. 
It would be nice to know why the unit tests are still taking so long.

**Comment by 2opremio** [comment]
@bboreham Are you planning to finish up this work anytime soon? Otherwise I would like to close it (I am cleaning up the lingering PRs)

**Comment by bboreham** [comment]
We need to move to CircleCI 2.0, which will perhaps provoke larger changes.
I think I'll leave this open as a constant reminder.

**Comment by bboreham** [comment]
Closing in favour of #3333 (which runs in about 14 minutes)

**Pull request closed without merging**
