### PR TITLE
Added linter and formatted tabs to 2 spaces

### PR DESCRIPTION
**Pull request by davkal**

### CODE REVIEW

**Comment by peterbourgon** [comment]
Forgive my ignorance, if I try to (run, commit, push) code that fails the linter, when/how do I know? Will Circle pick it up?

**Comment by davkal** [comment]
This PR only adds the linter. It wont break the build because currently the linter is not checked.

**Comment by tomwilkie** [comment]
Can we have two changes please?  on the fixes that tab, one that add the linter.  

Also please add a hook on circle to run the linter.

**Comment by davkal** [comment]
hmm, this means I have to disable 90% of rules and phase them in, because the rules I chose are quite comprehensive.

**Comment by davkal** [comment]
Currently at 388 errors. That might take me a while.

**Comment by tomwilkie** [comment]
Ah I see - you don't pass the lint right now? Yeah don't check it in then.

I would have a change which adds linting (including to circle), one which fixes whitespace, and one which fixes all the lint errors.

**Comment by davkal** [comment]
Ok, let me try some squashing then. What's needed for CI to pick up the linter? The command is `gulp lint`.

**Comment by tomwilkie** [comment]
I'd copy the line in the makefile for client-test:

```
client-lint:
	docker run -ti -v $(shell pwd)/client/app:/home/weave/app \
		-v $(shell pwd)/client/test:/home/weave/test \
		$(SCOPE_UI_BUILD_IMAGE) npm lint
```

And the corresponding line in circle.yml

**Comment by davkal** [comment]
Does the CI linter interface rely on the return code or on the output?

**Comment by tomwilkie** [comment]
Yes I believe so.

**Comment by tomwilkie** [comment]
This fixes #92

**Comment by davkal** [comment]
Last commit squashed the linter config commits

**Comment by tomwilkie** [comment]
LGTM

**Pull request merged**
