### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by 2opremio**
@davkal @foot @ekimekim @bowenli @jpellizzari @tomwilkie @jml @abuehrle @pidster @errordeveloper This is a major release, please chip in by testing this release branch in the scenarios below and tick off what you tested afterwards (including your name at the end). 

**EDIT:** To make things  easier to test I have pushed the image `weaveworks/scope:release-1.0-cd1e06b`

Thanks!

- [x] Start a 2 node cluster and leave a UI connected, watch for performance regression (Done by @2opremio)
- [x] Run a Scope cluster on ECS (Done by @2opremio)
- [x] Run Scope on https://github.com/microservices-demo/microservices-demo/
- [x] Run Scope on Docker For Mac
- [x] Start and stop Scope in standalone mode
  - [x] Linux
  - [x] docker-machine
- [x] Connect probes from release candidate to Weave Cloud
  - [x] Local scope in probe-only mode connects to Weave Cloud and renders correctly
    - [x] dev
    - [x] prod
  - [x] Controls appear for containers and function correctly (Done by @2opremio)
    - [x] dev
    - [x] prod
  - [x] No new errors in logging or telemetry
    - [x] dev
    - [x] prod

## Things to think about

- Kubernetes Integration
- CPU and memory usage

### CODE REVIEW

**Comment by jml** [comment]
Won't have time before the release, sorry.

**Comment by pidster** [comment]
I've tested on 
- SockShop locally (docker compose)
- D4M
- dev

**Comment by 2opremio** [comment]
Thanks @pidster. Can you tick it off from the check list?

**Comment by pidster** [comment]
I've ticked off the things I've tested

**Comment by abuehrle** [comment]
@fons I tested the latest on my ubuntu host and probes are not showing up in Weave Cloud, btw.  

It does start and stop, though.

**Comment by rade** [comment]
> It allowed me to include a command twice, i.e.: `weave launch weave launch token=<xxxx>`

@abuehrle you mean `scope launch`, right?

**Comment by abuehrle** [comment]
Yes,  I meant `scope launch`.  I will log this issue for you.   Probably a whole lot more tests we could do there as well.

**Comment by pidster** [comment]
I've tested docker-machine on MacOS.

**Comment by 2opremio** [comment]
> Start a 2 node cluster and leave a UI connected, watch for performance regression 

I actually updated the probes in the dev cluster https://github.com/weaveworks/service-conf/pull/324 and I observed they are consuming ~70% CPU which is pretty horrible but I don't think it's a regression. I am getting a CPU profile just in case.

**Comment by 2opremio** [comment]
Here it goes, nothing new is spiking up. However, conntrack's XML parser seems to be consuming too much CPU. I have noticed how the parser was less than optimal, but 42% CPU is big enough to consider switching to another parser.

probe-cpu

**Comment by pidster** [comment]
@2opremio is it worth replacing the conntrack parser if there's an alternative to conntrack in the pipe?

**Comment by 2opremio** [comment]
@pidster Please comment in the relevant issue https://github.com/weaveworks/scope/issues/1991

This issue is for the release (and we are not going to replace the parser before then)

**Pull request merged**
