### PR TITLE
Limit tables to 20 rows

### PR DESCRIPTION
**Pull request by 2opremio**
Should help with #1457 and #1454 until we have #985

### CODE REVIEW

**Comment by 2opremio** [comment]
@davkal Here's a sample report with the new trunction field in place: [report_truncation.json.gz](https://github.com/weaveworks/scope/files/257715/report_truncation.json.gz)

**Comment by rade** [comment]
What gets truncated by this besides container env vars?

**Comment by rade** [comment]
> What gets truncated by this besides container env vars?

AFAICT it is

- docker image labels
- docker container labels
- k8s labels

**Comment by 2opremio** [comment]
That is correct:
```
scope/probe$ grep -r AddTable *
docker/container.go:    result = result.AddTable(LabelPrefix, c.container.Config.Labels)
docker/container.go:    result = result.AddTable(EnvPrefix, c.env())
docker/reporter.go:             node = node.AddTable(ImageLabelPrefix, image.Labels)
kubernetes/meta.go:     }).AddTable(LabelPrefix, m.Labels())
```

**Comment by 2opremio** [comment]
@davkal Looking good

Two comments:

* Can we make it so that the message is shown when clicking not just hover?
* Maybe the copy could be slightly refined. 
Currently: _The section Environment Variables has been truncated because of too many entries.
714 entries are not shown. We are working on making this better._

I would propose _This section is too long and has been truncated (714 extra entries not included). We are working to remove this limitation._ 

I think it's more to the point and the section is obvious since it's name is right next to the warning sign.

**Comment by 2opremio** [comment]
@paul @foot Can you PTAL ?

**Comment by paulbellamy** [comment]
Looks good, I'd even drop _We are working on making this better._ Maybe just _714 entries hidden_ (which is all we say about filtered unconnected processes).

**Comment by paulbellamy** [comment]
backend code, LGTM.

**Comment by foot** [comment]
Code LGTM!

Copy about why we're truncating is kind of nice, explaining the situation a bit. But there are probably reasons not too. Like admission of imperfection in product or something.

I like
> We are working to remove this limitation.

**Comment by foot** [comment]
Should host.process-list/container-list be getting truncated? Those are 500+ on the attached report and make the UI a bit janky.

**Comment by 2opremio** [comment]
@foot That's tricker because ordering processes by CPU use etc ... require having them all to be useful.

**Comment by 2opremio** [comment]
LGTM

**Pull request merged**
