### PR TITLE
Procedural color creation for nodes

### PR DESCRIPTION
**Pull request by davkal**
Currently, colors are assigned at random order from a set of 20, leading to random color assignment across reloads.
Procedural color creation takes a string and maps it to the 360 degree color wheel, therefor colors will always be consistent across reloads.
* color hue is based on the first 2 letters of node rank
* color lightness is based on the first 2 letters of node label

screen shot 2015-11-20 at 14 48 51

### CODE REVIEW

**Comment by 2opremio** [comment]
This is the view of the service running under k8s:
screen shot 2015-11-23 at 5 07 40 pm

I wasn't expecting to see red or green. This was done with a fresh clone of this branch, after doing `make frontend` and `make static`

**Comment by 2opremio** [comment]
After a hard reload (to make sure it wasn't a caching problem) I still get reds and greens:

screen shot 2015-11-23 at 5 10 03 pm

Are colors supposed to be persistent now?

And can caching be actually a problem? Are filenames based on content? (i.e. hash-named)

**Comment by davkal** [comment]
Colors arent persisted, they are calculated based on node ranks and names.
You shouldnt get greens, nor reds. Could you gist a report, @2opremio ?

**Comment by 2opremio** [comment]
@davkal will do it later today (or tomorrow)

**Comment by 2opremio** [comment]
Here's another screenshot:

screen shot 2015-11-23 at 22 44 29

And its report: https://gist.github.com/2opremio/c297562cf54102a5eb11

**Comment by 2opremio** [comment]
> Colors arent persisted, they are calculated based on node ranks and names.

What I really meant is that their computation is now pure.

**Comment by davkal** [comment]
Looks like you didnt do `make frontend && make static && make`. 

Using `experimental/fixprobe` on that gist gives me:

screen shot 2015-11-24 at 16 19 05

@2opremio could u confirm?

**Comment by 2opremio** [comment]
I did `make frontend && make static && make` (in two environments). I can try it again but I am pretty sure I did.

**Comment by 2opremio** [comment]
And that's when I realize I was testing the base branch (`684-colors`) and not the feature branch (`procedural-colors`). My brain is to used to checkout whatever branch is in the PR heading which isn't `master`.

All good, merge away.

**Pull request merged**
