### PR TITLE
Show message in UI when topology too big to render

### LINKED ISSUE #474: Too many nodes for rendering should display an icon or error in the UI
Right now it's just a debug message, which makes diagnosing this issue a little difficult.

### PR DESCRIPTION
**Pull request by davkal**
screen shot 2015-09-16 at 12 52 52

Fixes #474

### CODE REVIEW

**Comment by peterbourgon** [comment]
Cool. Nit: "Please select a different topology" feels a bit... corporate? Disconnected? In some sense it's a problem that this happens, so I'd like to see something a bit more... human? "We're working on it, but for now, try a different topology?" — something like that?

**Comment by davkal** [comment]
screen shot 2015-09-16 at 15 32 12

**Comment by peterbourgon** [comment]
LGTM~

**Comment by tomwilkie** [comment]
We don't use the term topology else where in the UI, we might want to call it something else - view?

**Comment by peterbourgon** [comment]
Now that we've cut the release, this can be merged.

**Pull request merged**
